### PR TITLE
Allow Natural and Integer literals in binary notation

### LINKED ISSUE #1215: Binary literals
We love that dhall supports hexadecimal literals with the 0x prefix (https://github.com/dhall-lang/dhall-lang/issues/858)

How about adding similar support for binary?   with the 0b prefix?   (ex. 0b1001 yields 9)

### PR DESCRIPTION
**Pull request by kukimik**
Closes #1215.

Haskell implementation: https://github.com/dhall-lang/dhall-haskell/pull/2540.

### CODE REVIEW

**Review by Gabriella439 — APPROVED** [review]

**Comment by Gabriella439** [comment]
I'll also help you tie the knot by merging the corresponding Haskell PR so that this will pass the `dhall-lang` CI

**Comment by Gabriella439** [comment]
Oh wait, sorry, this can actually be fixed locally.  I think you need to update the reference implementation in this repository so that the tests pass.  In particular, you'll need to make a matching change here:

https://github.com/dhall-lang/dhall-lang/blob/master/standard/Parser.hs

**Comment by kukimik** [comment]
Fixed. Sorry, I missed that somehow. Thank you for pointing that out.

**Comment by Gabriella439** [comment]
Thank you for contributing this!

**Pull request merged**
