### PR TITLE
potPourriB.dhallb: Fix encoding of query string

### PR DESCRIPTION
**Pull request by sjakobi**
Original URL (potPourriA.dhall):

    https://-._~%2C!$&'*+;=:@0abc1--12a------a-a--a-0/foo?/-._~%2C!$&'*+;=:@/?

JSON representation of the original binary:

    [
        24,
        null,
        0,
        1,
        null,
        "-._~%2C!$&'*+;=:@0abc1--12a------a-a--a-0",
        "foo",
        "/-._~%2C!$&%27*+;=:@/?"
    ]

JSON representation of the new binary:

    [
        24,
        null,
        0,
        1,
        null,
        "-._~%2C!$&'*+;=:@0abc1--12a------a-a--a-0",
        "foo",
        "/-._~%2C!$&'*+;=:@/?"
    ]

Diff:

    9c9
    <     "/-._~%2C!$&%27*+;=:@/?"
    ---
    >     "/-._~%2C!$&'*+;=:@/?"

The query string was incorrectly percent-encoded.

### CODE REVIEW

**Comment by singpolyma** [comment]
+ should be percent-encoded because some servers interpret it as a space‎, following the CGI spec

**Comment by sjakobi** [comment]
> + should be percent-encoded because some servers interpret it as a space‎, following the CGI spec

That's an unrelated potential standard change, right?

Currently `+` is allowed as a `sub-delim`:

https://github.com/dhall-lang/dhall-lang/blob/5ca75a99355ab150845f1a205fcc7a4fc4b86ff5/standard/dhall.abnf#L587-L597

**Comment by philandstuff** [comment]
Query strings should be treated as opaque strings, and not decoded or encoded.  We have `tests/parser/success/unit/import/urls/escapedQueryA.dhall` to verify this behaviour.

It makes sense for us to decode and encode path segments, because we convert local paths to URL paths, which is an operation which involves manipulating the contents of a path.  But we don't ever do any manipulation of the contents of a query string, so we should just pass whatever the user gave us around in unmodified form.  Introducing percent-decoding or -encoding here just feels unnecessary and a source of subtle bugs; especially since (as you point out) the rules for percent-encoding and -decoding query strings are *not* the same as for paths.

**Comment by sjakobi** [comment]
Note that, before https://github.com/dhall-lang/dhall-lang/pull/627, the  `'` was not percent-encoded. So I really think that this patch is fix for a small regression – I really don't want to argue for a standard change here.

**Comment by Gabriel439** [comment]
@sjakobi: My understanding is that what is currently in `master` is what follows the standard since the standard does not specify to percent-encode query fragments.  So without a change to the standard then I believe we should not change the test result.

Also, in general the current standardization trend is towards preserving the original URL as much as possible (i.e. not percent-encoding the query fragment).  See https://github.com/dhall-lang/dhall-lang/issues/581 for the roadmap of URL-related changes

**Comment by sjakobi** [comment]
> My understanding is that what is currently in `master` is what follows the standard since the standard does not specify to percent-encode query fragments.

No. As I tried to point out in the PR description, `potPourriB.dhallb` in `master` _incorrectly_ uses percent encoding in the query string. The incorrect percent encoding was introduced in #627.

This PR will fix this.

**Comment by Gabriel439** [comment]
@sjakobi: Oh, I misread.  Yeah, then this looks good to me

**Pull request merged**
