### PR TITLE
Version 7.0.0 → 8.0.0

### PR DESCRIPTION
**Pull request by Gabriel439**
It's been ~30 days since the last release, so I figured I would cut a new release

I'm also aiming to get https://github.com/dhall-lang/dhall-lang/pull/560 into this release, since it should be ready in the next couple of days

### CODE REVIEW

**Comment by Gabriel439** [comment]
One thing I realized is that I had proposed to remove `Optional` literals in this release and old-style union literals in the next release.  Since I've forgotten do to the former for this release, I'll just delay each by one release, rather than cram something in at the last minute.

**Comment by philandstuff** [comment]
D’oh! In future, is it worth lining up planned deprecations as draft PRs?

**Comment by Gabriel439** [comment]
@philandstuff: Yeah, that would have been a good thing to do 🙂

**Comment by Gabriel439** [comment]
At this point I'm just waiting for 3 days since the last merged change.  I don't plan to wait for https://github.com/dhall-lang/dhall-lang/pull/571 since that's just a minor optimization for people who don't protect the Prelude with semantic integrity checks.  If necessary, we can cut another release for just the Prelude caching fix shortly after if people want.

**Pull request merged**
