### PR TITLE
Permit spaces around completion operator

### PR DESCRIPTION
**Pull request by Gabriel439**
This is motivated by the following discussion:

https://github.com/dhall-lang/dhall-haskell/issues/1513#issuecomment-552380939

... where people were surprised that the completion operator did not
permit surrounding spaces

### CODE REVIEW

**Comment by Gabriel439** [comment]
Matching change to the Haskell implementation here: https://github.com/dhall-lang/dhall-haskell/pull/1532

**Comment by sjakobi** [comment]
The `.dhallb` and `.diag` files for the test case are missing.

**Comment by Gabriel439** [comment]
@sjakobi: They're the same.  I just took the old unit test and added spaces to the expression

**Comment by sjakobi** [comment]
Ah, never mind then! I misread the diff.

**Pull request merged**
