### PR TITLE
Prelude: Simplify JSON rendering code a bit

### PR DESCRIPTION
**Pull request by sjakobi**
This manages to reduce the encoded size of the Prelude by ~~20%~~ ~~37%~~ 50%!

Motivation: https://discourse.dhall-lang.org/t/figuring-out-performance-bottlenecks/251/16

### CODE REVIEW

**Comment by sjakobi** [comment]
I've pushed an improvement to `List/uncons` that further reduces the Prelude cache size to a total of -37%.

The problem with `List/splitLast` was, that the input list `ls` appears 4 times in the normalized function body:

```dhall
λ(a : Type) →
λ(ls : List a) →
  { head =
      List/fold
        { index : Natural, value : a }
        (List/indexed a ls)
        (List a)
        ( λ(x : { index : Natural, value : a }) →
          λ(xs : List a) →
            if        Natural/isZero
                        ( Natural/subtract
                            x.index
                            (Natural/subtract 1 (List/length a ls))
                        )
                  ==  False
            then  [ x.value ] # xs
            else  xs
        )
        ([] : List a)
  , tail =
      List/fold
        { index : Natural, value : a }
        (List/indexed a ls)
        (List a)
        ( λ(x : { index : Natural, value : a }) →
          λ(xs : List a) →
            if    Natural/isZero
                    ( Natural/subtract
                        x.index
                        (Natural/subtract 1 (List/length a ls))
                    )
            then  [ x.value ] # xs
            else  xs
        )
        ([] : List a)
  }
```

Since these input lists are quite complicated terms once normalized, their duplication resulted in a large size increase.

With the new version of `List/uncons`, the input list appears only once in the function body.

**Comment by sjakobi** [comment]
More things to check:

* [ ] Define `List/uncons` via `List/unsnoc`. This doesn't seem to help with `Prelude` size, but might improve things once `render` is applied to things.
* [ ] In `renderJSONStruct`, we could try reducing the duplication of `block` by replacing `List/null` with `List/unsnoc` and using its results in the `if`-branches.

**Comment by sjakobi** [comment]
Here's a patch for `List/uncons` that would slightly increase the Prelude cache size again by ~4%.

```patch
 let List/uncons
     : ∀(a : Type) → List a → Optional (NonEmpty a)
     = λ(a : Type) →
       λ(ls : List a) →
-        Optional/map
-          a
-          (NonEmpty a)
-          (λ(head : a) → { head, tail = List/drop 1 a ls })
-          (List/head a ls)
+        merge
+          { None = None (NonEmpty a)
+          , Some =
+              λ(ny : NonYtpme a) →
+                Some { head = ny.last, tail = List/reverse a ny.init }
+          }
+          (List/unsnoc a (List/reverse a ls))
 
```

This is nicely "linear" (I hope that's the right term) in the `ls` argument, but in most implementations this would probably result in 3 passes over the list as compared to 1 with the original definition.

@timbertson Maybe you could test how this affects normalization times and cache sizes in your code. For now I'll leave it out of this PR.

**Comment by sjakobi** [comment]
I have found another "linear" version of `List/uncons` that seems like a good compromise to me. It _slightly_ increases cache sizes again, but I think it will be worth it once applied in user code.

I have included a comment to explain the rationale a bit.

**Comment by timbertson** [comment]
Nicely done @sjakobi. As I posted in the discourse thread, this speeds up my particular use case by ~35% right off the bat 👏

**Comment by timbertson** [comment]
(turns out LOC is not the only relevent metric: https://github.com/dhall-lang/dhall-lang/pull/936#issuecomment-599152677)

**Comment by sjakobi** [comment]
I'm having another look at `renderJSONStruct`, which seems like the likely culprit for the enormous size difference between `render` and `renderYAML`. Its `blocks` argument appears a whopping _30_ times in the normalized function body:

<details>

```dhall
λ(prefix : Text) →
λ(suffix : Text) →
λ ( blocks
  : { head : { head : Text, tail : List Text }
    , tail : List { head : Text, tail : List Text }
    }
  ) →
  if    Natural/isZero
          ( List/length
              Text
              (   ( merge
                      { None = blocks
                      , Some =
                          λ ( x
                            : { init : List { head : Text, tail : List Text }
                              , last : { head : Text, tail : List Text }
                              }
                            ) →
                            { head =
                                merge
                                  { None =
                                    { head = "${blocks.head.head},"
                                    , tail = [] : List Text
                                    }
                                  , Some =
                                      λ(x : { init : List Text, last : Text }) →
                                          blocks.head
                                        ⫽ { tail = x.init # [ "${x.last}," ] }
                                  }
                                  ( List/fold
                                      Text
                                      blocks.head.tail
                                      ( Optional
                                          { init : List Text, last : Text }
                                      )
                                      ( λ(x : Text) →
                                        λ ( acc
                                          : Optional
                                              { init : List Text, last : Text }
                                          ) →
                                          merge
                                            { None = Some
                                              { init = [] : List Text
                                              , last = x
                                              }
                                            , Some =
                                                λ ( ny
                                                  : { init : List Text
                                                    , last : Text
                                                    }
                                                  ) →
                                                  Some
                                                    (   ny
                                                      ⫽ { init = [ x ] # ny.init
                                                        }
                                                    )
                                            }
                                            acc
                                      )
                                      (None { init : List Text, last : Text })
                                  )
                            , tail =
                                  List/fold
                                    { head : Text, tail : List Text }
                                    x.init
                                    (List { head : Text, tail : List Text })
                                    ( λ(x : { head : Text, tail : List Text }) →
                                      λ ( `as`
                                        : List { head : Text, tail : List Text }
                                        ) →
                                          [ merge
                                              { None =
                                                { head = "${x.head},"
                                                , tail = [] : List Text
                                                }
                                              , Some =
                                                  λ ( x
                                                    : { init : List Text
                                                      , last : Text
                                                      }
                                                    ) →
                                                      x@1
                                                    ⫽ { tail =
                                                            x.init
                                                          # [ "${x.last}," ]
                                                      }
                                              }
                                              ( List/fold
                                                  Text
                                                  x.tail
                                                  ( Optional
                                                      { init : List Text
                                                      , last : Text
                                                      }
                                                  )
                                                  ( λ(x : Text) →
                                                    λ ( acc
                                                      : Optional
                                                          { init : List Text
                                                          , last : Text
                                                          }
                                                      ) →
                                                      merge
                                                        { None = Some
                                                          { init =
                                                              [] : List Text
                                                          , last = x
                                                          }
                                                        , Some =
                                                            λ ( ny
                                                              : { init :
                                                                    List Text
                                                                , last : Text
                                                                }
                                                              ) →
                                                              Some
                                                                (   ny
                                                                  ⫽ { init =
                                                                          [ x ]
                                                                        # ny.init
                                                                    }
                                                                )
                                                        }
                                                        acc
                                                  )
                                                  ( None
                                                      { init : List Text
                                                      , last : Text
                                                      }
                                                  )
                                              )
                                          ]
                                        # `as`
                                    )
                                    ( [] : List
                                             { head : Text, tail : List Text }
                                    )
                                # [ x.last ]
                            }
                      }
                      ( List/fold
                          { head : Text, tail : List Text }
                          blocks.tail
                          ( Optional
                              { init : List { head : Text, tail : List Text }
                              , last : { head : Text, tail : List Text }
                              }
                          )
                          ( λ(x : { head : Text, tail : List Text }) →
                            λ ( acc
                              : Optional
                                  { init :
                                      List { head : Text, tail : List Text }
                                  , last : { head : Text, tail : List Text }
                                  }
                              ) →
                              merge
                                { None = Some
                                  { init =
                                      [] : List
                                             { head : Text, tail : List Text }
                                  , last = x
                                  }
                                , Some =
                                    λ ( ny
                                      : { init :
                                            List
                                              { head : Text, tail : List Text }
                                        , last :
                                            { head : Text, tail : List Text }
                                        }
                                      ) →
                                      Some (ny ⫽ { init = [ x ] # ny.init })
                                }
                                acc
                          )
                          ( None
                              { init : List { head : Text, tail : List Text }
                              , last : { head : Text, tail : List Text }
                              }
                          )
                      )
                  ).head.tail
                # List/fold
                    { head : Text, tail : List Text }
                    ( merge
                        { None = blocks
                        , Some =
                            λ ( x
                              : { init : List { head : Text, tail : List Text }
                                , last : { head : Text, tail : List Text }
                                }
                              ) →
                              { head =
                                  merge
                                    { None =
                                      { head = "${blocks.head.head},"
                                      , tail = [] : List Text
                                      }
                                    , Some =
                                        λ ( x
                                          : { init : List Text, last : Text }
                                          ) →
                                            blocks.head
                                          ⫽ { tail = x.init # [ "${x.last}," ] }
                                    }
                                    ( List/fold
                                        Text
                                        blocks.head.tail
                                        ( Optional
                                            { init : List Text, last : Text }
                                        )
                                        ( λ(x : Text) →
                                          λ ( acc
                                            : Optional
                                                { init : List Text
                                                , last : Text
                                                }
                                            ) →
                                            merge
                                              { None = Some
                                                { init = [] : List Text
                                                , last = x
                                                }
                                              , Some =
                                                  λ ( ny
                                                    : { init : List Text
                                                      , last : Text
                                                      }
                                                    ) →
                                                    Some
                                                      (   ny
                                                        ⫽ { init =
                                                              [ x ] # ny.init
                                                          }
                                                      )
                                              }
                                              acc
                                        )
                                        (None { init : List Text, last : Text })
                                    )
                              , tail =
                                    List/fold
                                      { head : Text, tail : List Text }
                                      x.init
                                      (List { head : Text, tail : List Text })
                                      ( λ ( x
                                          : { head : Text, tail : List Text }
                                          ) →
                                        λ ( `as`
                                          : List
                                              { head : Text, tail : List Text }
                                          ) →
                                            [ merge
                                                { None =
                                                  { head = "${x.head},"
                                                  , tail = [] : List Text
                                                  }
                                                , Some =
                                                    λ ( x
                                                      : { init : List Text
                                                        , last : Text
                                                        }
                                                      ) →
                                                        x@1
                                                      ⫽ { tail =
                                                              x.init
                                                            # [ "${x.last}," ]
                                                        }
                                                }
                                                ( List/fold
                                                    Text
                                                    x.tail
                                                    ( Optional
                                                        { init : List Text
                                                        , last : Text
                                                        }
                                                    )
                                                    ( λ(x : Text) →
                                                      λ ( acc
                                                        : Optional
                                                            { init : List Text
                                                            , last : Text
                                                            }
                                                        ) →
                                                        merge
                                                          { None = Some
                                                            { init =
                                                                [] : List Text
                                                            , last = x
                                                            }
                                                          , Some =
                                                              λ ( ny
                                                                : { init :
                                                                      List Text
                                                                  , last : Text
                                                                  }
                                                                ) →
                                                                Some
                                                                  (   ny
                                                                    ⫽ { init =
                                                                            [ x
                                                                            ]
                                                                          # ny.init
                                                                      }
                                                                  )
                                                          }
                                                          acc
                                                    )
                                                    ( None
                                                        { init : List Text
                                                        , last : Text
                                                        }
                                                    )
                                                )
                                            ]
                                          # `as`
                                      )
                                      ( [] : List
                                               { head : Text, tail : List Text }
                                      )
                                  # [ x.last ]
                              }
                        }
                        ( List/fold
                            { head : Text, tail : List Text }
                            blocks.tail
                            ( Optional
                                { init : List { head : Text, tail : List Text }
                                , last : { head : Text, tail : List Text }
                                }
                            )
                            ( λ(x : { head : Text, tail : List Text }) →
                              λ ( acc
                                : Optional
                                    { init :
                                        List { head : Text, tail : List Text }
                                    , last : { head : Text, tail : List Text }
                                    }
                                ) →
                                merge
                                  { None = Some
                                    { init =
                                        [] : List
                                               { head : Text, tail : List Text }
                                    , last = x
                                    }
                                  , Some =
                                      λ ( ny
                                        : { init :
                                              List
                                                { head : Text
                                                , tail : List Text
                                                }
                                          , last :
                                              { head : Text, tail : List Text }
                                          }
                                        ) →
                                        Some (ny ⫽ { init = [ x ] # ny.init })
                                  }
                                  acc
                            )
                            ( None
                                { init : List { head : Text, tail : List Text }
                                , last : { head : Text, tail : List Text }
                                }
                            )
                        )
                    ).tail
                    (List Text)
                    ( λ(x : { head : Text, tail : List Text }) →
                        List/fold
                          Text
                          ([ x.head ] # x.tail)
                          (List Text)
                          (λ(a : Text) → λ(`as` : List Text) → [ a ] # `as`)
                    )
                    ([] : List Text)
              )
          )
  then  { head =
            "${prefix} ${( merge
                             { None = blocks
                             , Some =
                                 λ ( x
                                   : { init :
                                         List { head : Text, tail : List Text }
                                     , last : { head : Text, tail : List Text }
                                     }
                                   ) →
                                   { head =
                                       merge
                                         { None =
                                           { head = "${blocks.head.head},"
                                           , tail = [] : List Text
                                           }
                                         , Some =
                                             λ ( x
                                               : { init : List Text
                                                 , last : Text
                                                 }
                                               ) →
                                                 blocks.head
                                               ⫽ { tail =
                                                     x.init # [ "${x.last}," ]
                                                 }
                                         }
                                         ( List/fold
                                             Text
                                             blocks.head.tail
                                             ( Optional
                                                 { init : List Text
                                                 , last : Text
                                                 }
                                             )
                                             ( λ(x : Text) →
                                               λ ( acc
                                                 : Optional
                                                     { init : List Text
                                                     , last : Text
                                                     }
                                                 ) →
                                                 merge
                                                   { None = Some
                                                     { init = [] : List Text
                                                     , last = x
                                                     }
                                                   , Some =
                                                       λ ( ny
                                                         : { init : List Text
                                                           , last : Text
                                                           }
                                                         ) →
                                                         Some
                                                           (   ny
                                                             ⫽ { init =
                                                                     [ x ]
                                                                   # ny.init
                                                               }
                                                           )
                                                   }
                                                   acc
                                             )
                                             ( None
                                                 { init : List Text
                                                 , last : Text
                                                 }
                                             )
                                         )
                                   , tail =
                                         List/fold
                                           { head : Text, tail : List Text }
                                           x.init
                                           ( List
                                               { head : Text, tail : List Text }
                                           )
                                           ( λ ( x
                                               : { head : Text
                                                 , tail : List Text
                                                 }
                                               ) →
                                             λ ( `as`
                                               : List
                                                   { head : Text
                                                   , tail : List Text
                                                   }
                                               ) →
                                                 [ merge
                                                     { None =
                                                       { head = "${x.head},"
                                                       , tail = [] : List Text
                                                       }
                                                     , Some =
                                                         λ ( x
                                                           : { init : List Text
                                                             , last : Text
                                                             }
                                                           ) →
                                                             x@1
                                                           ⫽ { tail =
                                                                   x.init
                                                                 # [ "${x.last},"
                                                                   ]
                                                             }
                                                     }
                                                     ( List/fold
                                                         Text
                                                         x.tail
                                                         ( Optional
                                                             { init : List Text
                                                             , last : Text
                                                             }
                                                         )
                                                         ( λ(x : Text) →
                                                           λ ( acc
                                                             : Optional
                                                                 { init :
                                                                     List Text
                                                                 , last : Text
                                                                 }
                                                             ) →
                                                             merge
                                                               { None = Some
                                                                 { init =
                                                                     [] : List
                                                                            Text
                                                                 , last = x
                                                                 }
                                                               , Some =
                                                                   λ ( ny
                                                                     : { init :
                                                                           List
                                                                             Text
                                                                       , last :
                                                                           Text
                                                                       }
                                                                     ) →
                                                                     Some
                                                                       (   ny
                                                                         ⫽ { init =
                                                                                 [ x
                                                                                 ]
                                                                               # ny.init
                                                                           }
                                                                       )
                                                               }
                                                               acc
                                                         )
                                                         ( None
                                                             { init : List Text
                                                             , last : Text
                                                             }
                                                         )
                                                     )
                                                 ]
                                               # `as`
                                           )
                                           ( [] : List
                                                    { head : Text
                                                    , tail : List Text
                                                    }
                                           )
                                       # [ x.last ]
                                   }
                             }
                             ( List/fold
                                 { head : Text, tail : List Text }
                                 blocks.tail
                                 ( Optional
                                     { init :
                                         List { head : Text, tail : List Text }
                                     , last : { head : Text, tail : List Text }
                                     }
                                 )
                                 ( λ(x : { head : Text, tail : List Text }) →
                                   λ ( acc
                                     : Optional
                                         { init :
                                             List
                                               { head : Text, tail : List Text }
                                         , last :
                                             { head : Text, tail : List Text }
                                         }
                                     ) →
                                     merge
                                       { None = Some
                                         { init =
                                             [] : List
                                                    { head : Text
                                                    , tail : List Text
                                                    }
                                         , last = x
                                         }
                                       , Some =
                                           λ ( ny
                                             : { init :
                                                   List
                                                     { head : Text
                                                     , tail : List Text
                                                     }
                                               , last :
                                                   { head : Text
                                                   , tail : List Text
                                                   }
                                               }
                                             ) →
                                             Some
                                               (ny ⫽ { init = [ x ] # ny.init })
                                       }
                                       acc
                                 )
                                 ( None
                                     { init :
                                         List { head : Text, tail : List Text }
                                     , last : { head : Text, tail : List Text }
                                     }
                                 )
                             )
                         ).head.head} ${suffix}"
        , tail = [] : List Text
        }
  else  { head = prefix
        , tail =
              [ "  ${( merge
                         { None = blocks
                         , Some =
                             λ ( x
                               : { init : List { head : Text, tail : List Text }
                                 , last : { head : Text, tail : List Text }
                                 }
                               ) →
                               { head =
                                   merge
                                     { None =
                                       { head = "${blocks.head.head},"
                                       , tail = [] : List Text
                                       }
                                     , Some =
                                         λ ( x
                                           : { init : List Text, last : Text }
                                           ) →
                                             blocks.head
                                           ⫽ { tail = x.init # [ "${x.last}," ]
                                             }
                                     }
                                     ( List/fold
                                         Text
                                         blocks.head.tail
                                         ( Optional
                                             { init : List Text, last : Text }
                                         )
                                         ( λ(x : Text) →
                                           λ ( acc
                                             : Optional
                                                 { init : List Text
                                                 , last : Text
                                                 }
                                             ) →
                                             merge
                                               { None = Some
                                                 { init = [] : List Text
                                                 , last = x
                                                 }
                                               , Some =
                                                   λ ( ny
                                                     : { init : List Text
                                                       , last : Text
                                                       }
                                                     ) →
                                                     Some
                                                       (   ny
                                                         ⫽ { init =
                                                               [ x ] # ny.init
                                                           }
                                                       )
                                               }
                                               acc
                                         )
                                         ( None
                                             { init : List Text, last : Text }
                                         )
                                     )
                               , tail =
                                     List/fold
                                       { head : Text, tail : List Text }
                                       x.init
                                       (List { head : Text, tail : List Text })
                                       ( λ ( x
                                           : { head : Text, tail : List Text }
                                           ) →
                                         λ ( `as`
                                           : List
                                               { head : Text, tail : List Text }
                                           ) →
                                             [ merge
                                                 { None =
                                                   { head = "${x.head},"
                                                   , tail = [] : List Text
                                                   }
                                                 , Some =
                                                     λ ( x
                                                       : { init : List Text
                                                         , last : Text
                                                         }
                                                       ) →
                                                         x@1
                                                       ⫽ { tail =
                                                               x.init
                                                             # [ "${x.last}," ]
                                                         }
                                                 }
                                                 ( List/fold
                                                     Text
                                                     x.tail
                                                     ( Optional
                                                         { init : List Text
                                                         , last : Text
                                                         }
                                                     )
                                                     ( λ(x : Text) →
                                                       λ ( acc
                                                         : Optional
                                                             { init : List Text
                                                             , last : Text
                                                             }
                                                         ) →
                                                         merge
                                                           { None = Some
                                                             { init =
                                                                 [] : List Text
                                                             , last = x
                                                             }
                                                           , Some =
                                                               λ ( ny
                                                                 : { init :
                                                                       List Text
                                                                   , last : Text
                                                                   }
                                                                 ) →
                                                                 Some
                                                                   (   ny
                                                                     ⫽ { init =
                                                                             [ x
                                                                             ]
                                                                           # ny.init
                                                                       }
                                                                   )
                                                           }
                                                           acc
                                                     )
                                                     ( None
                                                         { init : List Text
                                                         , last : Text
                                                         }
                                                     )
                                                 )
                                             ]
                                           # `as`
                                       )
                                       ( [] : List
                                                { head : Text
                                                , tail : List Text
                                                }
                                       )
                                   # [ x.last ]
                               }
                         }
                         ( List/fold
                             { head : Text, tail : List Text }
                             blocks.tail
                             ( Optional
                                 { init : List { head : Text, tail : List Text }
                                 , last : { head : Text, tail : List Text }
                                 }
                             )
                             ( λ(x : { head : Text, tail : List Text }) →
                               λ ( acc
                                 : Optional
                                     { init :
                                         List { head : Text, tail : List Text }
                                     , last : { head : Text, tail : List Text }
                                     }
                                 ) →
                                 merge
                                   { None = Some
                                     { init =
                                         [] : List
                                                { head : Text
                                                , tail : List Text
                                                }
                                     , last = x
                                     }
                                   , Some =
                                       λ ( ny
                                         : { init :
                                               List
                                                 { head : Text
                                                 , tail : List Text
                                                 }
                                           , last :
                                               { head : Text, tail : List Text }
                                           }
                                         ) →
                                         Some (ny ⫽ { init = [ x ] # ny.init })
                                   }
                                   acc
                             )
                             ( None
                                 { init : List { head : Text, tail : List Text }
                                 , last : { head : Text, tail : List Text }
                                 }
                             )
                         )
                     ).head.head}"
              ]
            # (   List/fold
                    Text
                    (   ( merge
                            { None = blocks
                            , Some =
                                λ ( x
                                  : { init :
                                        List { head : Text, tail : List Text }
                                    , last : { head : Text, tail : List Text }
                                    }
                                  ) →
                                  { head =
                                      merge
                                        { None =
                                          { head = "${blocks.head.head},"
                                          , tail = [] : List Text
                                          }
                                        , Some =
                                            λ ( x
                                              : { init : List Text
                                                , last : Text
                                                }
                                              ) →
                                                blocks.head
                                              ⫽ { tail =
                                                    x.init # [ "${x.last}," ]
                                                }
                                        }
                                        ( List/fold
                                            Text
                                            blocks.head.tail
                                            ( Optional
                                                { init : List Text
                                                , last : Text
                                                }
                                            )
                                            ( λ(x : Text) →
                                              λ ( acc
                                                : Optional
                                                    { init : List Text
                                                    , last : Text
                                                    }
                                                ) →
                                                merge
                                                  { None = Some
                                                    { init = [] : List Text
                                                    , last = x
                                                    }
                                                  , Some =
                                                      λ ( ny
                                                        : { init : List Text
                                                          , last : Text
                                                          }
                                                        ) →
                                                        Some
                                                          (   ny
                                                            ⫽ { init =
                                                                    [ x ]
                                                                  # ny.init
                                                              }
                                                          )
                                                  }
                                                  acc
                                            )
                                            ( None
                                                { init : List Text
                                                , last : Text
                                                }
                                            )
                                        )
                                  , tail =
                                        List/fold
                                          { head : Text, tail : List Text }
                                          x.init
                                          ( List
                                              { head : Text, tail : List Text }
                                          )
                                          ( λ ( x
                                              : { head : Text
                                                , tail : List Text
                                                }
                                              ) →
                                            λ ( `as`
                                              : List
                                                  { head : Text
                                                  , tail : List Text
                                                  }
                                              ) →
                                                [ merge
                                                    { None =
                                                      { head = "${x.head},"
                                                      , tail = [] : List Text
                                                      }
                                                    , Some =
                                                        λ ( x
                                                          : { init : List Text
                                                            , last : Text
                                                            }
                                                          ) →
                                                            x@1
                                                          ⫽ { tail =
                                                                  x.init
                                                                # [ "${x.last},"
                                                                  ]
                                                            }
                                                    }
                                                    ( List/fold
                                                        Text
                                                        x.tail
                                                        ( Optional
                                                            { init : List Text
                                                            , last : Text
                                                            }
                                                        )
                                                        ( λ(x : Text) →
                                                          λ ( acc
                                                            : Optional
                                                                { init :
                                                                    List Text
                                                                , last : Text
                                                                }
                                                            ) →
                                                            merge
                                                              { None = Some
                                                                { init =
                                                                    [] : List
                                                                           Text
                                                                , last = x
                                                                }
                                                              , Some =
                                                                  λ ( ny
                                                                    : { init :
                                                                          List
                                                                            Text
                                                                      , last :
                                                                          Text
                                                                      }
                                                                    ) →
                                                                    Some
                                                                      (   ny
                                                                        ⫽ { init =
                                                                                [ x
                                                                                ]
                                                                              # ny.init
                                                                          }
                                                                      )
                                                              }
                                                              acc
                                                        )
                                                        ( None
                                                            { init : List Text
                                                            , last : Text
                                                            }
                                                        )
                                                    )
                                                ]
                                              # `as`
                                          )
                                          ( [] : List
                                                   { head : Text
                                                   , tail : List Text
                                                   }
                                          )
                                      # [ x.last ]
                                  }
                            }
                            ( List/fold
                                { head : Text, tail : List Text }
                                blocks.tail
                                ( Optional
                                    { init :
                                        List { head : Text, tail : List Text }
                                    , last : { head : Text, tail : List Text }
                                    }
                                )
                                ( λ(x : { head : Text, tail : List Text }) →
                                  λ ( acc
                                    : Optional
                                        { init :
                                            List
                                              { head : Text, tail : List Text }
                                        , last :
                                            { head : Text, tail : List Text }
                                        }
                                    ) →
                                    merge
                                      { None = Some
                                        { init =
                                            [] : List
                                                   { head : Text
                                                   , tail : List Text
                                                   }
                                        , last = x
                                        }
                                      , Some =
                                          λ ( ny
                                            : { init :
                                                  List
                                                    { head : Text
                                                    , tail : List Text
                                                    }
                                              , last :
                                                  { head : Text
                                                  , tail : List Text
                                                  }
                                              }
                                            ) →
                                            Some
                                              (ny ⫽ { init = [ x ] # ny.init })
                                      }
                                      acc
                                )
                                ( None
                                    { init :
                                        List { head : Text, tail : List Text }
                                    , last : { head : Text, tail : List Text }
                                    }
                                )
                            )
                        ).head.tail
                      # List/fold
                          { head : Text, tail : List Text }
                          ( merge
                              { None = blocks
                              , Some =
                                  λ ( x
                                    : { init :
                                          List { head : Text, tail : List Text }
                                      , last : { head : Text, tail : List Text }
                                      }
                                    ) →
                                    { head =
                                        merge
                                          { None =
                                            { head = "${blocks.head.head},"
                                            , tail = [] : List Text
                                            }
                                          , Some =
                                              λ ( x
                                                : { init : List Text
                                                  , last : Text
                                                  }
                                                ) →
                                                  blocks.head
                                                ⫽ { tail =
                                                      x.init # [ "${x.last}," ]
                                                  }
                                          }
                                          ( List/fold
                                              Text
                                              blocks.head.tail
                                              ( Optional
                                                  { init : List Text
                                                  , last : Text
                                                  }
                                              )
                                              ( λ(x : Text) →
                                                λ ( acc
                                                  : Optional
                                                      { init : List Text
                                                      , last : Text
                                                      }
                                                  ) →
                                                  merge
                                                    { None = Some
                                                      { init = [] : List Text
                                                      , last = x
                                                      }
                                                    , Some =
                                                        λ ( ny
                                                          : { init : List Text
                                                            , last : Text
                                                            }
                                                          ) →
                                                          Some
                                                            (   ny
                                                              ⫽ { init =
                                                                      [ x ]
                                                                    # ny.init
                                                                }
                                                            )
                                                    }
                                                    acc
                                              )
                                              ( None
                                                  { init : List Text
                                                  , last : Text
                                                  }
                                              )
                                          )
                                    , tail =
                                          List/fold
                                            { head : Text, tail : List Text }
                                            x.init
                                            ( List
                                                { head : Text
                                                , tail : List Text
                                                }
                                            )
                                            ( λ ( x
                                                : { head : Text
                                                  , tail : List Text
                                                  }
                                                ) →
                                              λ ( `as`
                                                : List
                                                    { head : Text
                                                    , tail : List Text
                                                    }
                                                ) →
                                                  [ merge
                                                      { None =
                                                        { head = "${x.head},"
                                                        , tail = [] : List Text
                                                        }
                                                      , Some =
                                                          λ ( x
                                                            : { init : List Text
                                                              , last : Text
                                                              }
                                                            ) →
                                                              x@1
                                                            ⫽ { tail =
                                                                    x.init
                                                                  # [ "${x.last},"
                                                                    ]
                                                              }
                                                      }
                                                      ( List/fold
                                                          Text
                                                          x.tail
                                                          ( Optional
                                                              { init : List Text
                                                              , last : Text
                                                              }
                                                          )
                                                          ( λ(x : Text) →
                                                            λ ( acc
                                                              : Optional
                                                                  { init :
                                                                      List Text
                                                                  , last : Text
                                                                  }
                                                              ) →
                                                              merge
                                                                { None = Some
                                                                  { init =
                                                                      [] : List
                                                                             Text
                                                                  , last = x
                                                                  }
                                                                , Some =
                                                                    λ ( ny
                                                                      : { init :
                                                                            List
                                                                              Text
                                                                        , last :
                                                                            Text
                                                                        }
                                                                      ) →
                                                                      Some
                                                                        (   ny
                                                                          ⫽ { init =
                                                                                  [ x
                                                                                  ]
                                                                                # ny.init
                                                                            }
                                                                        )
                                                                }
                                                                acc
                                                          )
                                                          ( None
                                                              { init : List Text
                                                              , last : Text
                                                              }
                                                          )
                                                      )
                                                  ]
                                                # `as`
                                            )
                                            ( [] : List
                                                     { head : Text
                                                     , tail : List Text
                                                     }
                                            )
                                        # [ x.last ]
                                    }
                              }
                              ( List/fold
                                  { head : Text, tail : List Text }
                                  blocks.tail
                                  ( Optional
                                      { init :
                                          List { head : Text, tail : List Text }
                                      , last : { head : Text, tail : List Text }
                                      }
                                  )
                                  ( λ(x : { head : Text, tail : List Text }) →
                                    λ ( acc
                                      : Optional
                                          { init :
                                              List
                                                { head : Text
                                                , tail : List Text
                                                }
                                          , last :
                                              { head : Text, tail : List Text }
                                          }
                                      ) →
                                      merge
                                        { None = Some
                                          { init =
                                              [] : List
                                                     { head : Text
                                                     , tail : List Text
                                                     }
                                          , last = x
                                          }
                                        , Some =
                                            λ ( ny
                                              : { init :
                                                    List
                                                      { head : Text
                                                      , tail : List Text
                                                      }
                                                , last :
                                                    { head : Text
                                                    , tail : List Text
                                                    }
                                                }
                                              ) →
                                              Some
                                                (   ny
                                                  ⫽ { init = [ x ] # ny.init }
                                                )
                                        }
                                        acc
                                  )
                                  ( None
                                      { init :
                                          List { head : Text, tail : List Text }
                                      , last : { head : Text, tail : List Text }
                                      }
                                  )
                              )
                          ).tail
                          (List Text)
                          ( λ(x : { head : Text, tail : List Text }) →
                              List/fold
                                Text
                                ([ x.head ] # x.tail)
                                (List Text)
                                ( λ(a : Text) →
                                  λ(`as` : List Text) →
                                    [ a ] # `as`
                                )
                          )
                          ([] : List Text)
                    )
                    (List Text)
                    (λ(x : Text) → λ(`as` : List Text) → [ "  ${x}" ] # `as`)
                    ([] : List Text)
                # [ suffix ]
              )
        }
```

</details>

Getting that multiplicity down to a more reasonable value should have a large impact.

**Comment by Gabriel439** [comment]
While we're on this subject, perhaps the top-level `package.dhall` should not re-export the JSON package?  People could still always import JSON separately.

I'm still in favor of these optimizations either way

**Comment by sjakobi** [comment]
I think I'll leave it at that for this PR. In sum, I ended up halving the Prelude cache size. I think there's still quite a bit of room to optimize `renderJSONStruct` further, particularly by fusing the multiple maps/folds. But I suspect that this will also affect readability quite badly, so it's better to discuss that on a separate patch.



> While we're on this subject, perhaps the top-level `package.dhall` should not re-export the JSON package? People could still always import JSON separately.

At 75kB, the cache for JSON/package.dhall is currently 82% of the entire Prelude cache, so I think users who don't use the JSON could benefit a bit from such a split. Maybe we should off on this until we've tried optimizing the rendering code a bit more though…

**Pull request merged**
