### PR TITLE
Remove union literals from the language

### PR DESCRIPTION
**Pull request by philandstuff**
Reducing the surface area of the language makes it easier for new
implementations 😇

This is raised as a draft PR because we're holding off actually doing this until.. v9.0 I think?

### CODE REVIEW

**Comment by Gabriel439** [comment]
@philandstuff: It doesn't have to be a draft pull request, but yeah, we're holding off until 9.0 (mainly to spread out breaking changes)

**Comment by philandstuff** [comment]
I just find "draft" to be a useful marker of "don't merge this yet", that's all.  But since we generally merge our own PRs, it doesn't matter much except as a statement of intent.

**Comment by joneshf** [comment]
Is there an issue where this change was discussed? It's a little tough to know what's being removed, what the alternative is, and what the migration strategy is just from the code changes.

**Comment by ocharles** [comment]
I believe this change is about the new syntax for union literals. You now write `Union-Type.Alternative Argument`. So you may have `< Red | Green | Blue>.Red` or `<Nothing | Just : Bool>.Just True`.

**Comment by Gabriel439** [comment]
@joneshf: See: https://github.com/dhall-lang/dhall-lang/wiki/Migration%3A-Deprecation-of-old-union-literal-syntax

**Comment by joneshf** [comment]
Thanks for the explanations!

**Comment by f-f** [comment]
This is good to merge now right?

**Comment by Gabriel439** [comment]
Yes, this is clear to merge

**Comment by sjakobi** [comment]
If you don't mind, could you add tests that check the legacy syntax now fails to parse, similarly to https://github.com/dhall-lang/dhall-lang/pull/620 or https://github.com/dhall-lang/dhall-lang/pull/629?

**Comment by philandstuff** [comment]
I've fixed up the conflicts (basically, making the new .diag files match the .dhallb changes) and added a test as @sjakobi suggested.  Now merging.

**Pull request merged**
