### PR TITLE
prelude: add xml rawText

### PR DESCRIPTION
**Pull request by ear7h**
See #1224 for more info

### CODE REVIEW

**Review by Gabriel439 — APPROVED** [review]
I'm fine with this if nobody else objects

**Comment by Gabriel439** [comment]
If you use `./scripts/lint-prelude.sh` then I believe it will get the hashes correct

**Comment by ear7h** [comment]
@Gabriel439 when I run it, haskell packages run into a weird linker error. I ran the lint and freeze commands manually and it looks like that part of CI passes. It's failing on mismatched test cases now

**Comment by Gabriel439** [comment]
@ear7h: https://github.com/dhall-lang/dhall-lang/pull/1228 will fix the scripts to work on Big Sur

**Pull request merged**
