### PR TITLE
Add a `Prelude.JSON.omitNullFields`

### PR DESCRIPTION
**Pull request by Gabriel439**
This is one step towards moving more `dhall-to-json` functionality into pure
Dhall.  This implements the `--omitNull` functionality of the
command-line tool.

### CODE REVIEW

**Comment by Nadrieril** [comment]
This doesn't seem to filter `[1, null, 2]` into `[1, 2]`; is this expected ?

(Also, you forgot to update the `preludeB` test)

**Comment by sjakobi** [comment]
> This is one step towards moving more `dhall-to-json` functionality into pure
> Dhall. This implements the `--omitNull` functionality of the
> command-line tool.

But `dhall-to-json` can't handle `Prelude.JSON.Type` as an input, right?

**Comment by Gabriel439** [comment]
@sjakobi: Actually, `dhall-to-json` can handle `Prelude.JSON.Type`:

```dhall
-- ./example.dhall
let JSON = https://prelude.dhall-lang.org/JSON/package.dhall

in  JSON.array [JSON.number 1.0, JSON.bool True ]
```
```bash
$ dhall-to-json --file ./example.dhall
[
  1,
  true
]
```

... although that's not what I meant.  What I mean is that given a Dhall value of type `A`, a package author could implement a pure Dhall function to convert `A`s to `JSON` and then use this utility to render that `JSON` as a YAML `Text` literal.

**Comment by Gabriel439** [comment]
@Nadrieril: Yes, that is intentional.  I can add another test along those lines

**Comment by sjakobi** [comment]
I think the name "filterNullFields" is slightly inconsistent with `List.filter`. In `List.filter`, the predicate determines the elements that we keep. Here, it's the null fields that we remove. Something like `removeNullFields` would be a bit better IMHO.

OTOH, a function that keeps only the null fields would be pretty useless, so most users can guess that `filterNullFields` filters the null fields _out_…

**Comment by Gabriel439** [comment]
@sjakobi: Another idea I had was that we could call it `omitNull`, for consistency with the `dhall-to-{json,yaml}` commands

**Comment by sjakobi** [comment]
> Another idea I had was that we could call it `omitNull`, for consistency with the `dhall-to-{json,yaml}` commands

That seems like a fine name! I expect that since that the `--omitNull` is the default now, we'll get rid of it at some point though.

**Comment by Gabriel439** [comment]
@sjakobi: Actually, I'll probably go with `omitNullFields`, just so that the name clarifies that it does not omit list elements

**Pull request merged**
