### PR TITLE
Add support for duplicate record fields

### PR DESCRIPTION
**Pull request by Gabriel439**
The motivation for this change is enable a subsequent change to the language
to add support for Nix/Cue/TOML-like short-hand syntax for records.

Specifically, we'd like to be able to write records using this
 "short-hand syntax":

```dhall
{ a.b = 1, a.c = True, b = "Hi!" }
```

... and have that desugar to:

```dhall
{ a = { b = 1, c = True }, b = "Hi!" }
```

I'm standardizing support for duplicate record fields in a separate step for
two reasons:

* For ease of implementation

  It's easier to implement, standardize, and to reason about the behavior of the
  "short-hand syntax" by decoupling it into two orthogonal changes to the
  language (of which this is the first change)

* To ensure the upcoming short-hand syntax behaves correctly in corner cases

I'll illustrate what I mean by the latter point.

As I mentioned above, all three of Nix, Cue, and TOML support a short-hand
syntax:

```nix
# Nix
{ a.b = 1;

  a.c = true;

  b = "Hi!";
}
```

```toml
# TOML
a.b = 1
a.c = true
b = "Hi!"
```

```cue
// Cue
a: b: 1
a: c: true
b: "Hi!"
```

However, TOML and Nix both misbehave on the following case:

```nix
# Nix
{ a.b = 1;

  a = { c = 1; };
}
```

```toml
# TOML
a.b = 1

[a]
c = 1
```

... and (as a NixOS user) this restriction has both surprised me and bitten me
on numerous occasions when trying to set NixOS configuration options.

Not only is this Nix/TOML behavior a poor user experience, but it also creates
theoretical issues, because you can no longer safely rewrite this:

```dhall
{ a.b = x, … }
```

... to this:

```dhall
{ a = { b = x }, … }
```

... because the `…` could be `a.c = 1`.

In fact, it's actually harder to implementing things the wrong way!  Simplifying
the implementation also fixes every corner case.

Cue, on the other hand, does not have the above problem, because Cue does
exactly what this change proposes.  When Cue encounters a duplicate field, the
interpreter recursively merges them and throws an error if there are any
field conflicts (just like Dhall's `∧` operator).

See the tests for additional examples and comments on how this should behave
in various cases.

### CODE REVIEW

**Comment by Gabriel439** [comment]
Here is the matching change to the Haskell implementation: https://github.com/dhall-lang/dhall-haskell/pull/1643

**Comment by Profpatsch** [comment]
What is the error message going to be for

```
{
  a = 4,

  … looooong document

  a.b = c
}
```

I can see that dhall doesn’t have the “unexpected” problem so much, because records are typed.

Is there a dual for sum types?

**Comment by Gabriel439** [comment]
@Profpatsch: Currently the error message is:

```
Use "dhall --explain" for detailed errors

Error: You can only combine records

 1│ { a = 4
 2│ , b = 0
 3│ , c = 0
 4│ , d = 0
 5│ , e = 0
 6│ , f = 0
 7│ , g = 0
 8│ , h = 0
 9│ , i = 0
10│ , j = 0
11│ , k = 0
12│ , l = 0
13│ , m = 0
14│ , n = 0
15│ , o = 0
16│ , p = 0
17│ , q = 0
18│ , r = 0
19│ , s = 0
20│ , t = 0
21│ , u = 0
22│ , v = 0
23│ , w = 0
24│ , x = 0
25│ , y = 0
26│ , z = 0
27│ , a = { b = 5 }
28│ }

./example.dhall:1:1
```

However, I want to add that we have the ability to improve the error message even though this is syntactic sugar.  For example, we did something similar for the `::` operator in https://github.com/dhall-lang/dhall-haskell/pull/1528.  That started out using the default error for the `//` / `:` operators it desugared to and then was tweaked to provide better messages specific to the `::` operator.

**Comment by sjakobi** [comment]
> The motivation for this change is enable a subsequent change to the language
> to add support for Nix/Cue/TOML-like short-hand syntax for records.
> 
> Specifically, we'd like to be able to write records using this
> "short-hand syntax":
> 
> ```haskell
> { a.b = 1, a.c = True, b = "Hi!" }
> ```

I think it would be good if we had a clear motivation for that short-hand syntax.

So far this is motivated only by the goal of supporting better nested overrides (https://github.com/dhall-lang/dhall-lang/issues/754#issuecomment-577773151), but that feels a bit "remote" – it seems possible that we'll still come up with a way of implementing those that doesn't rely on this record short-hand syntax.

It would be interesting to know why Nix, TOML and Cue support this short-hand. Perhaps they lack an equivalent to Dhall's `/\` operator!?

**Comment by Gabriel439** [comment]
@sjakobi: The short-hand syntax is a useful feature in its own right, which is why it was requested here: https://github.com/dhall-lang/dhall-lang/issues/220

In TOML's case, the short-hand syntax is necessary to represent nested records more than two levels deep.  Without it, the only other way would be to use inline JSON records (since TOML is a superset of JSON and JSON supports arbitrary record nesting).  Dhall does not have the same limitation as TOML so this rationale is not relevant to Dhall (but supporting the same syntax would still make Dhall more appealing to people familiar with TOML).

Nix added this feature mainly for ergonomic reasons and it makes a big difference in that regard.  Specifically, the NixOS module system deals with highly nested records of configuration options and you can see some real-world NixOS configurations in the code for Dhall's shared infrastructure here:

* https://github.com/dhall-lang/dhall-lang/blob/8cf71d94bd63710faae018aac0920b937b977b11/nixops/logical.nix
* https://github.com/dhall-lang/dhall-lang/blob/8cf71d94bd63710faae018aac0920b937b977b11/nixops/physical.nix

... and here are a few inline examples of that:

https://github.com/dhall-lang/dhall-lang/blob/8cf71d94bd63710faae018aac0920b937b977b11/nixops/logical.nix#L85

https://github.com/dhall-lang/dhall-lang/blob/8cf71d94bd63710faae018aac0920b937b977b11/nixops/logical.nix#L100

https://github.com/dhall-lang/dhall-lang/blob/8cf71d94bd63710faae018aac0920b937b977b11/nixops/logical.nix#L528

Being able to "compress" the field hierarchy can reduce a lot of syntactic clutter.  In fact, you will most commonly see this feature used to deal with very large and heavily-nested configuration formats (like `dhall-kubernetes` or NixOS configurations).

Also, there is a common idiom that takes advantage of this which you will see in both Nix and TOML.  Instead of writing this:

```nix
{ services = {
    openssh = {
      enable = true;
      forwardX11 = true;
    };

    hydra = {
      enable = true;
      extraConfig = ''
        …
      '';
    };
  }
}
```

... sometimes people instead prefer to write this:

```nix
{ services.openssh.enable = true;
  services.openssh.forwardX11 = true;

  services.hydra.enable = true;
  services.hydra.extraConfig = ''
    …
  '';
}
```

Handling duplicate fields enables that idiom because if you take the equivalent Dhall expression:

```dhall
{ services.openssh.enable = True
, services.openssh.forwardX11 = true

, services.hydra.enable = True
, services.hydra.extraConfig = ''
    …
  ''
}
```

... and desugar the short-hand syntax:

```dhall
{ services = { openssh = { enable = True } }
, services = { openssh = { forwardX11 = True } }
, services = { hydra = { enable = True } }
, services = { hydra = { extraConfig = "…" } }
}
```

... then the behavior for duplicate fields kicks in and merges them correctly to get:

```dhall
{ services = { openssh = { enable = True, forwardX11 = True } }
, services = { hydra = { enable = True, extraConfig = "…" } }
}
```

**Comment by sjakobi** [comment]
Thanks @Gabriel439. Your explanation makes this change look much more desirable to me!

Regarding the error message for incompatible duplicate fields: IMHO the introduction of `::` is not so comparable: Its implementation didn't reduce the quality of error messages for existing (buggy) code.

With the current proposal, errors for bugs that people have been writing for a long time become much worse. IMHO that should be addressed upfront. I don't know whether that requires a change to the proposal, but IMHO at least the Haskell implementation (https://github.com/dhall-lang/dhall-haskell/pull/1643) should improve the reported error for this case.

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, I can update the matching Haskell pull request to improve the error messages

**Comment by Nadrieril** [comment]
A more general comment is that we have no good way of explaining precisely the phases through which an expression passes as it's processed by an implementation. Someone might completely miss that this desugaring should be taking place because it's not menitoned in the grammar of the type inference rules. This for me is one more argument in favor of replacing the inference rules with an implementation in a mainstream language.

**Comment by Gabriel439** [comment]
Alright, after improving the error messages, this is the new output for a large record with the same field specified twice:

```
Error: Invalid duplicate field: a

Explanation: You can specify a field twice if both fields are themselves
records, like this:


    ┌──────────────────────────────────────────────────────────┐
    │ { ssh = { enable = True }, ssh = { forwardX11 = True } } │
    └──────────────────────────────────────────────────────────┘


... because the language automatically merges two occurrences of a field using
the ❰∧❱ operator, and the above example is equivalent to:


    ┌─────────────────────────────────────────────────────┐
    │ { ssh = { enable = True } ∧ { forwardX11 = True } } │
    └─────────────────────────────────────────────────────┘


... which is in turn equivalent to:


    ┌────────────────────────────────────────────────┐
    │ { ssh = { enable = True, forwardX11 = True } } │
    └────────────────────────────────────────────────┘


However, this implies that both fields must be records since the ❰∧❱ operator
cannot merge non-record values.  For example, these expressions are not valid:


    ┌──────────────────┐
    │ { x = 0, x = 0 } │  Invalid: Neither field is a record
    └──────────────────┘


    ┌──────────────────────────┐
    │ { x = 0, x = { y = 0 } } │  Invalid: The second ❰x❱ field is not a record
    └──────────────────────────┘


────────────────────────────────────────────────────────────────────────────────

You specified more than one field named:

↳ a

... but one of the fields had this value:

↳ 4

... with this type:

↳ Natural

... which is not a record type

────────────────────────────────────────────────────────────────────────────────

 1│ { a = 4
 2│ , b = 0
 3│ , c = 0
 4│ , d = 0
 5│ , e = 0
 6│ , f = 0
 7│ , g = 0
 8│ , h = 0
 9│ , i = 0
10│ , j = 0
11│ , k = 0
12│ , l = 0
13│ , m = 0
14│ , n = 0
15│ , o = 0
16│ , p = 0
17│ , q = 0
18│ , r = 0
19│ , s = 0
20│ , t = 0
21│ , u = 0
22│ , v = 0
23│ , w = 0
24│ , x = 0
25│ , y = 0
26│ , z = 0
27│ , a = { b = 5 }
28│ }

./example.dhall:1:1
```

**Comment by Gabriel439** [comment]
@Nadrieril: Yeah, I agree that this is a glaring omission in the standard documentation and replacing the natural deduction "code" with a simple reference implementation is probably the best solution to that problem

**Comment by ari-becker** [comment]
@Gabriel439 looks great, but -

>  │ { x = 0, x = { y = 0 } } │  Invalid: The second ❰x❱ field is not a record

You meant to write that the first field is not a record, not the second field, right?

**Comment by Gabriel439** [comment]
@ari-becker: Yes, that's correct.  I'll fix that.

**Pull request merged**
