### PR TITLE
Improve whitespace consistency

### PR DESCRIPTION
**Pull request by SupraSummus**
This PR changes nothing in respect to semantics, but makes standard a little bit more regular and easier to parse.

### CODE REVIEW

**Comment by Nadrieril** [comment]
Note that I plan to propose we replace the semantics with literate Haskell. It will break your attempts at parsing if that gets accepted.

**Comment by SupraSummus** [comment]
@Nadrieril thanks. Are there any issues/PRs/discussions about that change to literate haskell? I'd like to estimate how likely the change is and, as a result, whether it's sensible to make non semantic contributions to the current standard.

**Comment by Nadrieril** [comment]
@SupraSummus My own estimate is that it is reasonably likely to be accepted.
This idea has been floating around for a while. In particular @Gabriel439 mentioned it in [this comment](https://github.com/dhall-lang/dhall-lang/issues/735#issuecomment-529227798), and the response seemed rather positive. I made an attempt previously at replacing the semantics with code here https://github.com/dhall-lang/dhall-lang/issues/870 and it was rejected, but Haskell was mentioned again as a possibility.

**Comment by Gabriel439** [comment]
Yeah, I would accept a proposal for a literate Haskell or literate Agda semantics

**Pull request merged**
