### PR TITLE
adds Optional/show function

### PR DESCRIPTION
**Pull request by theNerd247**

### CODE REVIEW

**Comment by sjakobi** [comment]
This is a very different beast than the existing `*/show` functions.

In particular it cannot encode an `Optional` in a way that would result in the same `Optional` value when evaluated, like e.g. `Integer/show`:

```
⊢ Integer/show +1

"+1"
```

 What do you need it for?

**Comment by theNerd247** [comment]
So would the desired output be `Optional +1` ? I.E `read . show = id` ?

**Comment by sjakobi** [comment]
> So would the desired output be `Optional +1` ?

Maybe `Some +1`.

If you also want to show the original `None` value, you'd need another parameter for a `Text` representing the type – unless you implement it as a primitive.

So there appear to be quite a few different options.

I'm still wondering though: What's your usecase?

**Comment by Gabriel439** [comment]
I think the simplest solution here is to rename the function to `Text/optionalMap`, with a matching `Text/optional : Optional Text → Text` utility.  These utilities would essentially be the `Optional` analogs of `Text/concat` and `Text/concatMap`

As a side note, we could implement support for `show`ing `Optional` values and `List`s, but that would require substantially more work, like this:

```dhall
let Show : Type → Type = λ(a : Type) → { show : a → Text, showType : Text }

let Optional/Show
    : ∀(a : Type) → Show a → Show (Optional a)
    =   λ(a : Type)
      → λ(s : Show a)
      → { show =
              λ(o : Optional a)
            → Optional/fold
                a
                o
                Text
                (λ(x : a) → "Some (${s.show x})")
                "None (${s.showType})"
        , showType =
            "Optional ${s.showType}"
        }

let Natural/Show : Show Natural = { show = Natural/show, showType = "Natural" }

in  (Optional/Show Natural Natural/Show).show (None Natural)
```

... and getting rid of all of the parenthesis in the output would require even more work to encode precedence, too.  I think that's probably beyond what @theNerd247 had in mind, which is why I recommend reframing the original request as a function underneath the `Text/*` hierarchy.

**Comment by theNerd247** [comment]
I'm new to dhall but it seems there are no type-classes. For that reason I'm assuming implementing something like `Type/show` would also be non-trivial? If not then why not have `Optional/show` print the `a` type when `None` is matched.

If I may, could you explain the reasoning the language for the pattern `forall (a : Type) -> List a` where it seems in Haskell we just do `List a` and the compiler infers that a is a type parameter?

**Comment by theNerd247** [comment]
@sjakobi The use case is for a resume builder. I'm playing with `hakyll` where I had data stored in YAML files and wrote my own compiler for it...long story short it lead me to `dhall` and I've used @Gabriel439 's work regarding setting up a haskell dev system for nix. Figured I play with it.

I wanted `{ start: 2019, end: None Natural }` to be data for `{{start}} - {{end}}` in a resume section.

**Comment by joneshf** [comment]
If you know the different cases, you can encode them directly:
```Dhall
let date
    : Type
    = < past :
          { start : Natural, end : Natural }
      | current :
          { start : Natural }
      >

let render
    : date → Text
    =   λ(d : date)
      → merge
        { current =
            λ(config : { start : Natural }) → Natural/show config.start
        , past =
              λ(config : { start : Natural, end : Natural })
            → "${Natural/show config.start} - ${Natural/show config.end}"
        }
        d

let jobs
    : { job1 : date, job2 : date }
    = { job1 =
          date.past { start = 2016, end = 2019 }
      , job2 =
          date.current { start = 2019 }
      }

in  [ render jobs.job1, render jobs.job2 ]
```
```Dhall
[ "2016 - 2019", "2019" ]
```

**Pull request closed without merging**
