### PR TITLE
`dhall-rust` is now a complete language binding 🎉

### PR DESCRIPTION
**Pull request by Nadrieril**
It had been the case for a while but I had some loose ends to tie.
I've also added myself to the list of actively maintained implementations that get a vote on features, if that's okay.

### CODE REVIEW

**Comment by FintanH** [comment]
Nice one! 👏🙌

**Comment by SiriusStarr** [comment]
Great to hear!  (Especially since I'm finally getting around to learning Rust, haha.)

**Comment by Nadrieril** [comment]
How can I add dhall-rust to the list of integrations listed on the official dhall website ?

**Comment by sjakobi** [comment]
> How can I add dhall-rust to the list of integrations listed on the official dhall website ?

Make a PR against `dhall-haskell`: https://github.com/dhall-lang/dhall-haskell/blob/ef0a6589ee08eae2fada7024081523442dcc41f8/dhall-try/index.html#L135-L157

**Comment by Gabriel439** [comment]
@Nadrieril: The dhall-lang.org code lives here:

https://github.com/dhall-lang/dhall-haskell/blob/master/dhall-try/README.md

Specifically, you'll add HTML to the `index.html` page here:

https://github.com/dhall-lang/dhall-haskell/blob/ef0a6589ee08eae2fada7024081523442dcc41f8/dhall-try/index.html#L135-L158

... and then add Nix logic for fetching the Rust logo here:

https://github.com/dhall-lang/dhall-haskell/blob/ef0a6589ee08eae2fada7024081523442dcc41f8/nix/shared.nix#L37-L116

... and installing the logo here:

https://github.com/dhall-lang/dhall-haskell/blob/ef0a6589ee08eae2fada7024081523442dcc41f8/nix/website.nix#L23-L37

**Comment by sjakobi** [comment]
@Nadrieril could you also add `dhall-rust` to the list of integrations on dhall-lang.org? See https://github.com/dhall-lang/dhall-haskell/pull/1481 for a similar change.

**Comment by Nadrieril** [comment]
Yeah I've been meaning to do it for a while, but work is getting in the way for now

**Comment by Gabriel439** [comment]
@Nadrieril: Don't worry!  I can take care of this

**Comment by Gabriel439** [comment]
Here is the pull request to add Rust to dhall-lang.org: https://github.com/dhall-lang/dhall-haskell/pull/1623

**Comment by Nadrieril** [comment]
@Gabriel439 Thank you very much ! :heart: I was for some reason dreading to try and do this PR myself :persevere:

**Comment by Gabriel439** [comment]
@Nadrieril: You're welcome! 🙂

**Pull request merged**
