### PR TITLE
Simplify record projection of a single field via field selection

### PR DESCRIPTION
**Pull request by sjakobi**
Inspired by #661.

### CODE REVIEW

**Comment by singpolyma** [comment]
Shouldn't this just say `t.{x} -> v | t.x -> v` ?

**Comment by sjakobi** [comment]
> Shouldn't this just say `t.{x} -> v | t.x -> v` ?

I'm not quite sure what you mean, but this is a rule for normalizing record projections, not for normalizing field selections.

**Comment by singpolyma** [comment]
On re-reading, I've realised why the extra record construction is needed.

**Comment by Gabriel439** [comment]
It seems like this would actually be easier to implement if generalized to an arbitrary number of fields.  i.e.:

```dhall
r.{ x, y, z } = { x = r.x, y = r.y, z = r.z }
```

**Comment by sjakobi** [comment]
@Gabriel439 Generalizing this to an arbitrary number of fields would make things more consistent and slightly easier to implement. I was a bit worried about duplicating the argument though: that might lead us to evaluate it repeatedly which might hurt performance. Maybe I'm overestimating this?!

It would admittedly allow more simplifications and also simplify the standard…

**Comment by Gabriel439** [comment]
Then I think we should probably hold off on this.  In particular, I think we need more examples of use cases where this rewrite would come in handy.  My main reservation about this is that when applied in isolation it makes the code more syntactically repetitive (i.e. `r.{ x }` getting rewritten to `{ x = r.x }`).  In my view the whole reason behind using the `.{ x }` notation is to avoid having to specify the field name twice.

Another reason I think we should hold off on this is that the user can already work-around non-optimal normalizations by explicitly applying this code transformation to their own code (i.e. manually rewriting their uses of `r.{ x }` to `{ x = r.x }` when normalization get stuck).

**Comment by sjakobi** [comment]
Makes sense @Gabriel439!

I might revisit this idea in the context of simplifying a surrounding `//` or `/\`.

**Pull request closed without merging**
