### PR TITLE
Make normalization tests type-correct

### PR DESCRIPTION
**Pull request by Nadrieril**
I propose we make all normalization tests type-correct from now on. [This has been suggested before](https://github.com/dhall-lang/dhall-lang/pull/605#issuecomment-505938167), though at the time I was against it.

The reasons I advocate for this change are:
- We always typecheck before normalizing, so in practice normalization will never encounter an ill-typed expression;
- knowing that type information will always be present allows me to simplify my implementation quite a bit, and I'm guessing this applies to other implementations;
- if we ever want type-directed normalization rules, we'll need tests to be type-correct;
- it makes it easier to generate the `B` side of tests, by using `dhall normalize`.

I've fixed a dozen tests for now but a lot remain; I'll do the rest if you guys think it's a good idea

### CODE REVIEW

**Comment by Nadrieril** [comment]
I fixed all the tests. And that unearthed quite a few errors of my implementation on the typed path x)

**Comment by singpolyma** [comment]
My biggest issue with this is that it makes the "unit" tests much less unitary because they mostly need to also exercise lambda introduction on top of whatever was already there.

If there are code paths this tests that weren't tested before, that's interesting, but seems to be like it would be more indicative of missing tests rather than a deficiency in these ones?

I actually *don't* always type check before normalizing in dhall-ruby, because there are cases where "calling" a Dhall function from Ruby with something that "quacks like a duck" is useful, since Ruby is not statically typed itself.  Though of course the vast majority of normalizations take place after typechecking and I've had some rules that take advantage of that (such as an experiment normalizing old union syntax to new union syntax).

**Comment by Nadrieril** [comment]
> My biggest issue with this is that it makes the "unit" tests much less unitary because they mostly need to also exercise lambda introduction on top of whatever was already there.

Yeah that's why I was against that for a while. Now I think lambda is a small and important enough feature that I don't mind assuming it's implemented.

> 
> If there are code paths this tests that weren't tested before, that's interesting, but seems to be like it would be more indicative of missing tests rather than a deficiency in these ones?

That's specific to my implementation. It's because when I typecheck before normalizing I reuse some of the work from typechecking (like variable resolution), and that had never been tested.

**Comment by sjakobi** [comment]
> knowing that type information will always be present allows me to simplify my implementation quite a bit, and I'm guessing this applies to other implementations;

@AndrasKovacz could this be useful for your NbE branch of the Haskell implementation?

**Comment by Nadrieril** [comment]
I'll go ahead and merge this then

**Pull request merged**
