### PR TITLE
Add section about Prelude in README

### PR DESCRIPTION
**Pull request by f-f**
Following up from #140, I added a section where we can link all the distributions/packagings of Prelude.

I'm not sure the section is in the right place of the document, and I think we're missing `nixpkgs` as @Profpatsch [suggested](https://github.com/dhall-lang/dhall-lang/issues/140#issuecomment-386294126) (but I wasn't able to get it from there, so I'm not quite sure how to put that into words/links).

### CODE REVIEW

**Comment by f-f** [comment]
@Profpatsch this is interesting, I cannot make the two commands you posted to work on this machine (`nix` on macOS), but `nix-env -f "<nixpkgs>" -iA dhall.prelude` works nicely. Should I include this one?

**Comment by Profpatsch** [comment]
Apparently they changed it to not output a path to the generated path(s) anymore. The `result` symlink(s) is(/are) generated though. I personally don’t use `nix env` (because it introduces state), but I suspect many people do.

**Comment by Gabriel439** [comment]
Also note that the Prelude has been relocated to https://github.com/dhall-lang/Prelude

I'll be removing the Prelude from the Haskell repository soon to reflect that.  I've already updated `http://prelude.dhall-lang.org` to start serving the Prelude from the new repository

**Comment by Profpatsch** [comment]
> I'll be removing the Prelude from the Haskell repository soon to reflect that.

What’s your strategy to keep the nixpkgs version up-to-date then? I liked that the prelude was bound to the reference implementation, meaning there was no way for it to be incompatible. We are losing that now.

**Comment by f-f** [comment]
> What’s your strategy to keep the nixpkgs version up-to-date then? I liked that the prelude was bound to the reference implementation, meaning there was no way for it to be incompatible. We are losing that now.

This is a good concern.
A possible solution for this could be to submodule the Prelude repo in `dhall-haskell`, so that the derivation for Prelude can fetch the submodule at the correct compatible commit.

**Comment by Gabriel439** [comment]
@Profpatsch: I can still keep the Prelude mirrored in the `dhall-haskell` project since that will probably make it easier to build and maintain.  However, at some point we still need a language-independent repository to be the source of truth for the Prelude if we want to support multiple implementations.  The important point is that proposed changes to the Prelude go there instead of against the Haskell implementation

If anything, I think it might make sense to merge it into this repository (so that changes to the Prelude are made in sync with changes to the standard), but then that would make it a little trickier to distribute (it's not just `git clone` any longer)

**Comment by Profpatsch** [comment]
> I can still keep the Prelude mirrored in the dhall-haskell project since that will probably make it easier to build and maintain.

I think that would be a lot easier for downstream, yes.

**Comment by Gabriel439** [comment]
@f-f: I think you can go ahead and merge this

@Profpatsch: I'll keep the Prelude mirrored in the Haskell implementation

**Pull request merged**
