### PR TITLE
Add normalization test for (Natural/subtract 0)

### PR DESCRIPTION
**Pull request by sjakobi**
This turned out to be a tricky case for the Haskell implementation
(see https://github.com/dhall-lang/dhall-haskell/pull/1194).

### CODE REVIEW

**Comment by sjakobi** [comment]
Alternatively we could change the rule

```
x ⇥ 0   y₀ ⇥ y₁
──────────────────────────
Natural/subtract x y₀ ⇥ y₁
```

to 

```
x ⇥ 0
───────────────────────────────────────
Natural/subtract x ⇥ λ(n : Natural) → n
```

(and it should probably be

```
f ⇥ Natural/subtract   x ⇥ 0
───────────────────────────────────────
f x ⇥ λ(n : Natural) → n
```
)

**Comment by philandstuff** [comment]
I disagree with allowing `Natural/subtract 0` to normalise further.  Currently, every built in function has a specific arity at which it gets normalized - so you can determine if `f x` is in normal form simply by normalising `f` and then inspecting it. Introducing functions which have normalisation rules which consume different numbers of arguments sounds like it adds extra implementation complexity (and would prevent a refactoring I’m currently thinking of doing in dhall-golang).

**Comment by sjakobi** [comment]
Merging, as this does not appear to be standard change in the sense of https://github.com/dhall-lang/dhall-lang/blob/master/.github/CONTRIBUTING.md#how-do-changes-get-approved.

**Comment by Gabriel439** [comment]
@sjakobi: Yes, that's correct.  Test changes only require a 24-hour review period

**Pull request merged**
