### PR TITLE
Setup CORS testing endpoints on test.dhall-lang.org

### PR DESCRIPTION
**Pull request by Nadrieril**
I didn't test this, hope it works. If it does we'll be able to write the actual tests.
Part of https://github.com/dhall-lang/dhall-lang/issues/1130

### CODE REVIEW

**Review by Gabriel439 — APPROVED** [review]
This looks great!  I'll test this locally on a virtual machine soon and if it works then I'll merge

**Comment by Gabriel439** [comment]
I verified locally that this serves the correct headers for one of the endpoints:

```bash
$ curl --request OPTIONS --verbose --insecure https://localhost:8443/cors/AllowedAll.dhall 
*   Trying ::1:8443...
* TCP_NODELAY set
* connect to ::1 port 8443 failed: Connection refused
*   Trying 127.0.0.1:8443...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=test.dhall-lang.org
*  start date: May  1 04:28:12 2021 GMT
*  expire date: May 31 04:28:12 2023 GMT
*  issuer: CN=minica root ca 58e360
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x22de860)
> OPTIONS /cors/AllowedAll.dhall HTTP/2
> Host: localhost:8443
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 204 
< server: nginx
< date: Sat, 01 May 2021 04:34:52 GMT
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
< access-control-max-age: 600
< content-type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact

$ curl --request GET --verbose --insecure https://localhost:8443/cors/AllowedAll.dhall    
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1:8443...
* TCP_NODELAY set
* connect to ::1 port 8443 failed: Connection refused
*   Trying 127.0.0.1:8443...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=test.dhall-lang.org
*  start date: May  1 04:28:12 2021 GMT
*  expire date: May 31 04:28:12 2023 GMT
*  issuer: CN=minica root ca 58e360
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x74c860)
> GET /cors/AllowedAll.dhall HTTP/2
> Host: localhost:8443
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx
< date: Sat, 01 May 2021 04:34:56 GMT
< content-type: text/plain
< vary: Accept-Encoding
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
< access-control-expose-headers: Content-Length,Content-Range
< 
42
* Connection #0 to host localhost left intact
```

**Comment by Nadrieril** [comment]
Thanks!

**Comment by Gabriel439** [comment]
You're welcome! 🙂

**Pull request merged**
