### PR TITLE
Add failure test for duplicated record fields to typecheck suite

### PR DESCRIPTION
**Pull request by f-f**
Now that I'm adding a test explicitly for this I wanted to find the place in the standard in which we disallow this, but I wasn't able to find it..

### CODE REVIEW

**Comment by f-f** [comment]
Thinking more about this:
- I'm adding this test as a typecheck error, but in the standard we don't specify anywhere that this error should happen at typecheck time (AFAIK)
- I think this failure should happen at parsing time, because a record with duplicated fields is nonsensical already at parsing time

**Comment by Gabriel439** [comment]
@f-f: How would we specify in the grammar that a record can't have a duplicate field?

**Comment by Gabriel439** [comment]
Also, we do specify that duplicate fields can't happen at type-check time.  For example:

```
Γ ⊢ T :⇥ Type   Γ ⊢ { xs… } :⇥ Type
───────────────────────────────────  ; x ∉ { xs… }
Γ ⊢ { x : T, xs… } : Type
```

The `x ∉ { xs… }` is the key bit

**Comment by f-f** [comment]
Right, thanks 👍 Then I'll just add a mention to this near that rule, so it's easier to grep for "duplicated" or something similar

**Pull request merged**
