### PR TITLE
tidy up record projection

### PR DESCRIPTION
**Pull request by philandstuff**
This adds more tests for record projection, and tidies up the beta-normalization text for record projection.

This adds:

 * a binary-decode test

 * a type-inference test for the base case typing judgment rule

 * a type-inference test for the judgmental equality behaviour
   introduced in #597

 * typecheck failure tests for cases which should fail

It also:

 * adds projection-by-type to the list of expressions in
   standard/README.md.

 * migrates a beta-normalization rule for field selection which somehow
   got removed from the other field selection rule.

 * uses two blank lines consistently around judgments

 * makes it clear that you can use an empty record type as a selector in
   a project-by-type expression, by using `{ ss… }` notation instead of
   `{ x : T, ss… }`

 * removes the normalization judgment for `t₀.(s₀) ⇥ t₁.(s₁)` that could
   never match

The last point deserves more explanation.  The expression `t.(s)` can
only typecheck if `s ⇥ { ss… }`, which means that we can always
normalize a `t.(s)` expression to a `t.{ ss… }` expression using the
rule above.  Because the `t₀.(s₀) ⇥ t₁.(s₁)` judgment only matches "If
no other rule matches", and because the other rule always matches, it is
redundant and can be removed.

### CODE REVIEW

**Comment by singpolyma** [comment]
> Because the t₀.(s₀) ⇥ t₁.(s₁) judgment only matches "If n‎o other rule matches", and because the other rule always matches, it is r‎edundant and can be removed.

Normalization is not dependent on typechecking. So just because no fully-typechecked expression could match that does not mean it's redundant.

**Comment by philandstuff** [comment]
On Sun, 23 Jun 2019 at 00:38, Stephen Paul Weber <notifications@github.com>
wrote:

> Normalization is not dependent on typechecking. So just because no
> fully-typechecked expression could match that does not mean it's redundant


If you don’t typecheck before you normalize, you no longer have any
guarantee that it will terminate. So I’m not sure under what circumstances
we would be happy to normalize something that hasn’t been typechecked.

**Comment by Gabriel439** [comment]
@philandstuff: I think it's fine to remove those judgments if we replace them with a comment saying that no other cases need to be handled if the expression is well-typed

**Comment by sjakobi** [comment]
I noticed that some test names are a bit inconsistent too, making them harder to find:

```diff
-tests/normalization/success/unit/RecordProjectionTypeEmpty*
+tests/normalization/success/unit/RecordProjectionByTypeEmpty*
```

```diff
-tests/normalization/success/unit/RecordProjectionTypeNonEmpty*
+tests/normalization/success/unit/RecordProjectionByTypeNonEmpty*
```

```diff
-tests/type-inference/success/unit/RecordProjectionType*
+tests/type-inference/success/unit/RecordProjectionByType*
```

**Comment by sjakobi** [comment]
> I noticed that some test names are a bit inconsistent too, making them harder to find:

Another one:

```diff
-tests/parser/success/recordProjectionByExpression*
+tests/parser/success/RecordProjectionByType*
```

**Comment by philandstuff** [comment]
I pushed a couple of commits to address comments from @Gabriel439 and @sjakobi.  I'll merge once hydra goes green.

**Pull request merged**
