### PR TITLE
Allow trailing delimiters

### LINKED ISSUE #512: Allow trailing delimiters
As far as I understand, one of the major pain points when writing JSON by hand (and thus one of the reasons for migrating to YAML) is the lack of trailing commas.
I understand trailing delimiters were omitted from Dhall [because they complexify the grammar](https://github.com/dhall-lang/dhall-haskell/issues/27#issuecomment-330892244). However, with the current focus of displacing YAML, I think Dhall would benefit from supporting trailing (and/or leading ?) delimiters.
As anecdotal evidence, a friend of mine mentionned the lack of trailing commas as one of the reasons Dhall did not feel mature to them.

### PR DESCRIPTION
**Pull request by Nadrieril**
Fixes #512.
I discovered that the grammar allowed `{ , = }` for an empty record literal. I'm not sure if we want to keep that.

### CODE REVIEW

**Comment by Profpatsch** [comment]
Doesn’t allowing a trailing delimiter require backtracking all the way?

**Comment by Gabriel439** [comment]
@Profpatsch: I believe it's still doable without full backtracking.  Using commas as an example, after parsing any given comma-separated element you parse one of:

```haskell
    try ("," *> whsp *> "})
<|> try "}"
<|> ("," *> parseElement *> parseRest)
```

... which limits backtracking to a limited number of characters

**Comment by Nadrieril** [comment]
Isn't that lookahead rather than backtracking then ? I don't remember that being a performance sink

**Comment by Nadrieril** [comment]
Does anyone object to this then ?

**Comment by Gabriel439** [comment]
@Nadrieril: I still think this proposal is a good idea

**Comment by Gabriel439** [comment]
I think this is ready to be merged

**Comment by Nadrieril** [comment]
Yeah sorry I haven't had the bandwidth for dhall recently, and I wanted to add the tests that @philandstuff suggested

**Pull request merged**
