### PR TITLE
Allow Sort as type annotation

### PR DESCRIPTION
**Pull request by Nadrieril**
Fixes https://github.com/dhall-lang/dhall-lang/issues/454.
I didn't want to add a new judgment so instead I added a special case to the type annotation rule:
```
Γ ⊢ t : Sort
─────────────────────
Γ ⊢ (t : Sort) : Sort
```
I also simplified the `merge`-with-type-annotation rule to allow for `merge x y : Sort`.

### CODE REVIEW

**Comment by singpolyma** [comment]
I believe `tests/typecheck/failure/unit/Sort.dhall` should remain, since `Sort` alone still cannot be typed.

**Comment by Gabriel439** [comment]
@singpolyma: It would be valid if you interpret the type-checking suite as taking each `A.dhall` expression and adding the `B.dhall` expression as a type annotation

**Comment by singpolyma** [comment]
@Gabriel439 oh, right. My bad

**Comment by Nadrieril** [comment]
@singpolyma I think you were correct; `Sort` still cannot be on the left of a type annotation. I'll re-add the test

**Pull request merged**
