### PR TITLE
Fix referentially opaque Prelude test

### PR DESCRIPTION
**Pull request by Gabriel439**
The deleted test causes the Prelude to fail when imported remotely
due to failing the referential sanity check.

The right solution here is to make `missing` a valid transitive import
for remote imports, but this is a quick fix to restore Prelude
functionality until then.

### CODE REVIEW

**Comment by Gabriel439** [comment]
@f-f @singpolyma: Could you review this quickly when you have the chance?  This breaks `https://prelude.dhall-lang.org/package.dhall` at the moment and I'd like to cut an `11.1.0` point release to fix this

**Comment by amarrella** [comment]
Can we get a release of this one? :)

**Comment by Gabriel439** [comment]
@amarrella: I think it's a case of where the contributing process is ambiguous here: it doesn't specify if a change requires a unanimous vote or a majority vote to be merged early (i.e. after 3 days).  I have always been interpreting it to mean a unanimous vote (at least, for my own contributions), but if people don't object I can relax it to a majority vote and go ahead and merge.

**Comment by amarrella** [comment]
No worries, I'm happy to wait the 3 days, I'm just using this to warm a cache

**Pull request merged**
