### PR TITLE
upgrade dhall-k8s to v6.0

### PR DESCRIPTION
**Pull request by jcouyang**

### CODE REVIEW

**Comment by Gabriel439** [comment]
Thank you! 🙂

**Comment by jcouyang** [comment]
hi @Gabriel439
now I can find k8s v6 on store.dhall.com, I'm assuming cache should be hosted there as well
but i got 404
```
> dhall hash <<< 'https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/v6.0.0/1.21/package.dhall'
sha256:9d07ad4eff6d388aaf7c4715d3b83812a7eee8a6281a5e64098aaddb3551ce6a
> curl -i https://store.dhall-lang.org/12209d07ad4eff6d388aaf7c4715d3b83812a7eee8a6281a5e64098aaddb3551ce6a
HTTP/2 404
```
did I miss any steps?

**Comment by Gabriel439** [comment]
@jcouyang: It's because the kubernetes package cached by store.dhall-lang.org is for the top-level `package.dhall`, which re-exports `./1.17/package.dhall`, not `./1.21/package.dhall`

I double-checked that the `./1.17/package.dhall` is the version that is being cached in store.dhall-lang.org (hash: `sha256:532e110f424ea8a9f960a13b2ca54779ddcac5d5aa531f86d82f41f8f18d7ef1`):

```ShellSession
$ dhall hash <<< 'https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/v6.0.0/package.dhall'
sha256:532e110f424ea8a9f960a13b2ca54779ddcac5d5aa531f86d82f41f8f18d7ef1
$ curl --head https://store.dhall-lang.org/1220532e110f424ea8a9f960a13b2ca54779ddcac5d5aa531f86d82f41f8f18d7ef1 
HTTP/2 200 
server: nginx
date: Sun, 28 Nov 2021 18:31:06 GMT
content-type: application/dhall+cbor
content-length: 2308085
etag: "af1xbsf13wzccxgk0a59dl975mf2z1rh"
accept-ranges: bytes
```

However, if you want we could host multiple Kubernetes versions on store.dhall-lang.org (e.g. `dhall-kubernetes-vX.Y.Z-vX.Y.Z`, where the first version is the `dhall-kubernetes` version and the second version is the kubernetes API version).  Alternatively, we could change the default kubernetes version re-exported by the top-level `./package.dhall`.

**Comment by jcouyang** [comment]
thanks @Gabriel439 , i think it makes sense to have both
to have default package point to the latest k8s schema version
as well as hosting maybe last 2-3 versions of k8s schema for each `dhall-kubernetes` version
I can send another PR accordingly

**Pull request merged**
