### PR TITLE
Add recommendation for `cbor2diag` in tests' readme

### LINKED ISSUE #656: .dhallb ergonomics
Working with tests for the binary encoding and reviewing changes to `.dhallb` files is currently tricky as the binary files are hard to read and GitHub can't show the diffs.

I think it would be better to include the JSON representations of the binaries. We could

1. Replace the `.dhallb` with `.json` files produced by [`cbor-tool dump --json`](http://hackage.haskell.org/package/cbor-tool). Implementations would then have to encode the JSON files to check their binary decoders.

2. Add the JSON files in addition to the `.dhallb` files and use CI to check their equivalence.

### PR DESCRIPTION
**Pull request by f-f**
Fix #656

### CODE REVIEW

**Comment by sjakobi** [comment]
That's a good change but IMHO not a sufficient fix for #656.

**Comment by Gabriel439** [comment]
I think you can specify this in the `.gitattributes` file so that users don't need to remember to modify their own `git` configuration

**Comment by f-f** [comment]
@Gabriel439 we already have this line in `.gitattributes` to tell `git` to treat diffs to `.dhallb` files as `cbor`:
```
*.dhallb diff=cbor
```

Looking at the [docs for `gitattributes`](https://git-scm.com/docs/gitattributes) it seems that instructing `git` on how to render `cbor` diffs must be done in the `.git/config`, so I think the user has to set it manually there (cc @philandstuff, any ideas?)

**Comment by philandstuff** [comment]
@f-f yup, that’s my understanding too

**Comment by ocharles** [comment]
This looks good to me, shall we move ahead with merging?

**Comment by f-f** [comment]
@ocharles I'm not sure anymore this is useful now that we version the rendered files

**Comment by ocharles** [comment]
Ahh, true. So time to close?

**Comment by f-f** [comment]
Not sure. @Gabriel439 opinions?

**Comment by Gabriel439** [comment]
Yeah, I think this is superseded by the `*.diag` files, so I'll close this

**Pull request closed without merging**
