### PR TITLE
Add `Location` type to Prelude

### PR DESCRIPTION
**Pull request by Gabriel439**

### CODE REVIEW

**Comment by sjakobi** [comment]
Should `Location` be included in the main `package.dhall`?

**Comment by Gabriel439** [comment]
@sjakobi: It can't be, because it's a type and the language does not support mixed records of terms and types (although we could fix that)

**Comment by sjakobi** [comment]
Ah, right!

We could have a `types.dhall` in addition to the `package.dhall` though, if there's demand…

**Comment by Gabriel439** [comment]
@sjakobi: It's actually not hard to standardize support for mixed records.  I just keep forgetting to do so.

Basically, you change the type-checking judgments for records so that the type of a record type is just the upper bound of the type of its field types (which I understand is what Agda does to support this).  In other words:

```haskell
{ foo = 1 } : { foo : Integer } : Type

{ bar = Bool } : { bar : Type } : Kind

{ foo = 1, bar = Bool } : { foo : Integer, bar : Type } : Kind 
```

**Comment by sjakobi** [comment]
@Gabriel439 In https://github.com/dhall-lang/dhall-lang/pull/120 you explained why mixed records don't seem to fit into Dhall's type system. Have things changed since, that would allow them to be brought back?

**Comment by f-f** [comment]
@sjakobi since then we implemented the [CCω](https://hal.inria.fr/hal-01445835/document) typesystem (the same as Coq) in #272, which allows this (you might also be interested in taking a look at #250 where mixed records are discussed too

**Comment by Gabriel439** [comment]
@sjakobi: There were two separate problems with the first attempt at mixed records:

* The inferred type of the records was wrong

  This is the mistake that led to the type system backdoor.  Specifically, the problem was that:

  ```dhall
  { t : Type } : Type
  ```

  ... when it should have been:

  ```dhall
  { t : Type } : Kind
  ```

  The incorrect inferred type is what led to the backdoor because it allowed hiding a type inside of a record that outwardly appeared to be a term.  The above sketch fixes that problem because if you stuff a type inside of a record then the type system can no longer treat the record as a term.

* The second issue was that System F doesn't let you encode such a record but Dhall is now based on CCω, as @f-f just noted :slightly_smiling_face:

**Pull request merged**
