### PR TITLE
Integer negate and clamp

### PR DESCRIPTION
**Pull request by SiriusStarr**
PR for proposed addition of `Integer/negate` and `Integer/clampToNatural` builtins per discussion on [Discourse](https://discourse.dhall-lang.org/t/dealing-with-negative-numbers/88).

Someone smarter than I needs to confirm the beta-normalization for `Integer/negate` is correct, please.  :laughing: 

Additionally, it should be noted that, as `Integer/clampToNatural` is longer than other builtin names, it overflows the lined-up equals signs in the ABNF (line 406 in the diff of `standard/dhall.abnf`).  I did not reformat the extant entries to match this longer name so as to avoid introducing a much larger whitespace diff, but I can obviously do so if that's desired.

### CODE REVIEW

**Comment by Gabriel439** [comment]
@SiriusStarr: Maybe shorten `Integer/clampToNatural` to `Integer/clamp` since I can't think of any other type we would be clamping `Integer` to.  That would also side-step the alignment problem 🙂

**Comment by sjakobi** [comment]
> Maybe shorten `Integer/clampToNatural` to `Integer/clamp` since I can't think of any other type we would be clamping `Integer` to.

`Integer/clamp` could have type `Integer -> Integer`…

But if everyone's in favor of the shorter name, I wouldn't mind it.

**Comment by SiriusStarr** [comment]
Updating to `Integer/clamp` (and caught a typo in the beta normalization), gimme a few minutes.

**Comment by SiriusStarr** [comment]
@sjakobi RE parser tests, it doesn't look like other builtins have them (not seeing one for `Natural/subtract`, for example)?  Could you point me to an example?

**Comment by SiriusStarr** [comment]
RE the prelude, shall I add some or all of the utilities discussed on Discourse as well, (e.g. `nonPositive`, `positive`, `nonNegative`, `negative`, `toNatural` (the `Optional` version), and `abs`)?

**Comment by sjakobi** [comment]
> RE parser tests, it doesn't look like other builtins have them (not seeing one for `Natural/subtract`, for example)? Could you point me to an example?

Oh, never mind then.

> RE the prelude, shall I add some or all of the utilities discussed on Discourse as well

That would be great! But maybe wait a bit in case there are some fundamental disagreements over the proposal.

**Comment by SiriusStarr** [comment]
Okay, this should be ready for review/comments/whatnot.  I will add the builtins to the prelude if/when it's accepted.

**Comment by Gabriel439** [comment]
@SiriusStarr: At this point, we're just waiting either for 7 days to pass or for all three approvals, whichever comes first.  For more details, see: https://github.com/dhall-lang/dhall-lang/blob/master/.github/CONTRIBUTING.md#how-do-changes-get-approved

**Comment by SiriusStarr** [comment]
Yep, I read as much, but thanks for the update.

**Comment by singpolyma** [comment]
I'm curious if `Integer/build : Natural -> <Positive | Negative> -> Integer` would be more like what we want (especially in light of the desire for `clamp` or for an Integer destructing here).

**Comment by SiriusStarr** [comment]
@singpolyma You mean instead of `Integer/negate`?

**Comment by singpolyma** [comment]
>@singpolyma You mean instead of `Integer/negate`?

Yes

**Comment by sjakobi** [comment]
> `Integer/build : Natural -> <Positive | Negative> -> Integer`

If we'd add this instead of `Integer/negate`, we couldn't recover the absolute value of a negative `Integer`.

It might be a good addition to the Prelude though!

**Comment by Gabriel439** [comment]
Note that we can create an `Integer/build` in the Prelude from `Integer/negate` + `Natural/toInteger`

**Comment by singpolyma** [comment]
> If we'd add this instead of Integer/negate, we couldn't recover the absolute value of a negative Integer.

Would not:

    Integer/build (Integer/clamp (-1)) (<Negative|Positive>.Positive)

Get the absolute value of a negative Integer?

I realize that `build` can be make out of other parts, but the reason I propose `build` is that it is in line with other things already in the language and acts as the natural introducer for an Integer -- whereas `negate` acts more like an operation *on* an Integer (of which we currently do not have any).

**Comment by singpolyma** [comment]
Oh, I see, I misread.  `clamp` is going to turn negative numbers to zero?  That seems very odd...

**Comment by singpolyma** [comment]
Alright, sorry all for my being slow.  I've re-read the discourse thread and got the context more properly in my mind.  I still don't love having a `negate` operation but the best I can come up with to cover all three things without this is indeed three builtins instead, which runs rather counter to my anti-built-in nature as well:

    Integer/build : Natural -> <Negative|Positive> -> Integer
    Integer/abs : Integer -> Natural
    Integer/sign : Integer -> <Negative|Positive>

**Comment by sjakobi** [comment]
> I still don't love having a `negate` operation

What's the problem with it?

**Comment by singpolyma** [comment]
@sjakobi As I said, `negate` would introduce an operation on `Integer`, which we currently have none of, and then it would be the only one.  It feels quite odd to have `Integer` be "opaque except you can negate it"

**Comment by sjakobi** [comment]
> It feels quite odd to have `Integer` be "opaque except you can negate it"

With `Integer/negate`, `Integer/clamp` and `Natural/toInteger`, `Integer` just really isn't opaque anymore.

I think an alternative could be change most of the `Natural` operations to work on `Integer`, which would allow more efficient computations on `Integer`, but I currently don't think it's worth the trouble.

**Comment by philandstuff** [comment]
@singpolyma recognising the danger of topic drift here, I don't think your proposed `Integer/build` fits the language pattern for build functions.  I expect a build function to:

 - take one function as a parameter (and possibly some types before hand)
 - call the function, passing it constructors of the data type

So I would expect `Integer/build` to have type

	∀ ( f : ∀(integer : Type)
          → ∀(nonNegative : Natural → integer)
          → ∀(negative : Natural → integer)
          → integer
          )
      → Integer

where we have modelled an Integer as `< NonNegative Natural | Negative Natural >`.  I would also expect there to be a corresponding `fold` function as the canonical destructor for `Integers`.

I don't actually think this would be a valuable addition to the language; my main argument is that if we add your proposed function, we don't call it `Integer/build` because it violates my expectations about what `Integer/build` would be if it existed.

**Comment by SiriusStarr** [comment]
Agreed, elsewhere in Dhall, `build` is always the inverse of `fold`, so it would be weird for it to not be that way for integers.

**Comment by Gabriel439** [comment]
@SiriusStarr: This should be good to merge now.  I can take care of the corresponding changes in the Haskell implementation

**Comment by SiriusStarr** [comment]
@Gabriel439 Shall I open a second PR for the prelude additions?  They're ready to go but unsure how to finalize them until `dhall-haskell` is updated with the new builtins, since I can't generate the hashes for the imports.

**Comment by Gabriel439** [comment]
@SiriusStarr: Yeah, I think it's fine if the Prelude additions go in a second pull request

**Comment by Gabriel439** [comment]
@SiriusStarr: Also, here is the matching change to the Haskell implementation:

https://github.com/dhall-lang/dhall-haskell/pull/1486

**Comment by sjakobi** [comment]
@SiriusStarr Is this ready to be merged from your side?

**Comment by SiriusStarr** [comment]
@sjakobi  Should be good to go, since there have been no further comments/suggestions.  Prelude additions are up separately as #797

**Pull request merged**
