### PR TITLE
Add white space to empty lines inside rules

### PR DESCRIPTION
**Pull request by travisbrown**
More nitpickery in the same line as #368.

From [RFC 5234](https://tools.ietf.org/html/rfc5234):
```
         rule           =  rulename defined-as elements c-nl
                                ; continues if next line starts
                                ;  with white space
```
And the implementation, which makes it clear that a blank line inside a rule must contain whitespace:
```
...
         c-wsp          =  WSP / (c-nl WSP)

         c-nl           =  comment / CRLF
                                ; comment or newline
...
         alternation    =  concatenation
                           *(*c-wsp "/" *c-wsp concatenation)

         concatenation  =  repetition *(1*c-wsp repetition)
...
         WSP            =  SP / HTAB
                                ; white space
```
Some ABNF processors will fail on the blank lines I've replaced here.

### CODE REVIEW

**Comment by travisbrown** [comment]
@f-f Yep, APG is pretty picky about this stuff.

**Comment by travisbrown** [comment]
The build failure here is just a Clojars 503—I confirmed that instaparse is fine with these changes locally, so I think a maintainer just needs to restart the build.

**Comment by Gabriel439** [comment]
@travisbrown: I just restarted the build

**Comment by Gabriel439** [comment]
@travisbrown: Just added you as a collaborator so you can merge yourself after the minimum 3-day review period is done

**Comment by travisbrown** [comment]
Just merged master to resolve conflict with #377.

**Comment by Gabriel439** [comment]
@travisbrown: You can merge the pull request now that the minimum 3-day review period is complete and you have the necessary approvals

**Pull request merged**
