### PR TITLE
Fix RFC5234-compliance of the grammar

### PR DESCRIPTION
**Pull request by Nadrieril**
Without this, my ABNF parsing library rejected the file

### CODE REVIEW

**Comment by Gabriel439** [comment]
@Nadrieril: If you can explain how you consume the file I can see if I can add the same check to CI

**Comment by Nadrieril** [comment]
I'm using [this Rust library](https://crates.io/crates/abnf) to parse the abnf and convert it into something that can generate parser code. This lib is barely maintained and pretends to succeed when the input doesn't parse. I don't think it's worth the effort to try and make a CI check out of that.

**Comment by Nadrieril** [comment]
Should I wait for 3 days or am I allowed to merge early since this doesn't change any semantics ?

**Comment by Gabriel439** [comment]
@Nadrieril: Anything underneath the `./standard` directory (including the grammar), requires the minimum 3-day waiting period

**Comment by Gabriel439** [comment]
Note that we could adjust the contributing instructions to relax that rule, though

**Pull request merged**
