### PR TITLE
Create `store.dhall-lang.org`

### PR DESCRIPTION
**Pull request by Gabriel439**
For more details, see:

https://discourse.dhall-lang.org/t/rfc-proxy-dhall-lang-org/144/3?u=gabriel439

The short summary is that we can declaratively add Dhall packages to
cache and make that cache available from `store.dhall-lang.org`.

The path of a cached item is the item's multihash.  So, for example,
the address of version 13.0.0 of the Prelude would be:

https://store.dhall-lang.org/12204aa8581954f7734d09b7b21fddbf5d8df901a44b54b4ef26ea71db92de0b1a12

Interpreters can then optionally avail themselves of this shared cache,
either automatically or with explicit user consent, in order to speed up
package imports.

Most of the changes are due to the fact that this required upgrading Nixpkgs
in order to pick up the Nixpkgs support for building Dhall packages.

### CODE REVIEW

**Comment by Gabriel439** [comment]
Note that this might not yet safe to merge because of the following issue:

https://discourse.nixos.org/t/upcoming-hydra-schema-change/5806

Specifically, `hydra` requires a manual migration step when upgrading Nixpkgs.

I'm currently inquiring for more details to see how exactly to orchestrate the `hydra`
migration safely while using our continuous delivery setup as closely as possible.

**Comment by philandstuff** [comment]
@sjakobi we use multihash as the cache key precisely so that the requester can specify which version they want to fetch.  Multiple versions of the same resource can exist in the cache simultaneously (so the dhall-kubernetes pre-binary-coding-change and post-change both exist and are cached). 

It's also worth noting that the design of protocol here doesn't really use HTTP caching features (`Cache-control`, `Etag` and friends) - which I think is a good thing.  All it does is creates a read-only content-addressable store, where URLs are multihashes.

My only concern about this protocol is that, by not providing the upstream URL of the import to the proxy, we don't provide a way for the proxy to fetch the content itself if it wants to.  We can contrast this with the [go module proxy protocol](https://golang.org/cmd/go/#hdr-Module_proxy_protocol) where requests to a go module proxy provide the module name (`<module>` in the linked document), which can be converted to a URL by the proxy for fetching purposes.

**Comment by sjakobi** [comment]
> @sjakobi we use multihash as the cache key precisely so that the requester can specify which version they want to fetch. Multiple versions of the same resource can exist in the cache simultaneously (so the dhall-kubernetes pre-binary-coding-change and post-change both exist and are cached).

I understand that both versions can coexist in the cache. But my current understanding of the Nix deployment process is, that with each deployment the cache is erased and re-generated. So any pre-binary-coding-change caches would be lost. Is that understanding incorrect?

**Comment by Gabriel439** [comment]
@sjakobi: That is correct; the cache has no history because the directory of cached products is always built from a clean slate.

However, it is possible for us to cache more than one package set for multiple versions of `dhall`.  It takes a little bit of Nix work to wire things up, but it's definitely possible.

**Comment by Gabriel439** [comment]
Alright, I verified that this is working via a test deploy after backing up the `hydra` database.  The main thing that needed to be fixed was the `hydra-evaluator` patch, which was patching the wrong build.

I had actually done the migration incorrectly: I didn't correctly deploy the `hydra-migration` package as instructed and accidentally jumped straight to the `hydra-unstable` package because I misunderstood the instructions.  However, I was able to fix things, by:

* Restoring the `hydra` database from a backup
* Running the `hydra-backfill-ids` script
* Removing `/var/lib/hydra/.db-created`
* Restarting the `hydra-init` service

... and then things were back to normal.  On the bright side, we no longer require a second step after this migration, because I accidentally jumped the middle step. :slightly_smiling_face: 

I also did a health check for the following:

* dhall-lang.org
* discourse.dhall-lang.org
* hydra.dhall-lang.org
* cache.dhall-lang.org
* store.dhall-lang.org
* the mail server that Discourse uses

There's only one thing I noticed that is out of the ordinary, which is that Hydra reports spurious evaluation failures in the UI for PR builds preceding the migration, but under the hood the evalution actually succeeds (it's just a UI bug).  Also, new CI runs after the migration are unaffected by this UI bug.

**Comment by Gabriel439** [comment]
I also tested CI on a new pull request, too: https://github.com/dhall-lang/dhall-haskell/pull/1782

**Pull request merged**
