### PR TITLE
fix types in parser tests

### PR DESCRIPTION
**Pull request by philandstuff**
The parser tests had a number of cases where they had Natural and
Integer syntax swapped round.  This presumably dates from before #138
switched the grammar of Integer and Natural.

Note that this difference doesn't actually matter for these parsing
tests, because an expression like `+1 : Natural` still parses correctly,
it just fails to typecheck.  But I found it confusing to have the syntax
so consistently backwards in the tests, so I thought it was worth
changing.

### CODE REVIEW

**Comment by philandstuff** [comment]
Oops, I realised I need to also change the *B.dhall files. I won’t get to that for a little while - but I’ll leave this open in the mean time.

**Comment by Gabriel439** [comment]
@philandstuff: I opened a pull request to update the tests for your branch: https://github.com/philandstuff/dhall-lang/pull/1

**Comment by philandstuff** [comment]
I've merged your PR - this one should now be ready to go

**Comment by Gabriel439** [comment]
Oh wait, I forgot that changes to just the tests don't require the 3-day review period.  I'll go ahead and merge

**Pull request merged**
