### PR TITLE
Update dhall-haskell

### PR DESCRIPTION
**Pull request by sjakobi**
This changes the formatting of Dhall source files affected by dhall-lang/dhall-haskell#183 or dhall-lang/dhall-haskell#1400.

The change in Prelude/Text/show is due to dhall-lang/dhall-haskell#1508, but also relies the bug fixes
dhall-lang/dhall-haskell/pull/1543 and dhall-lang/dhall-haskell/pull/1550.

### CODE REVIEW

**Comment by sjakobi** [comment]
Oops! Looks like I broke `Prelude/Text/show`:

[Before](https://github.com/dhall-lang/dhall-lang/blob/3b31dea1ba47f9de041a7288826f07a05a167ba7/Prelude/Text/show), [after](https://github.com/dhall-lang/dhall-lang/blob/2c7db0afdcceba0d83e1a7e2e20604f166522f81/Prelude/Text/show) – GitHub doesn't show the unescaped NULL character at the beginning of the multi-line string.

**Comment by sjakobi** [comment]
Apart from the errors due to the bad formatting, the build log contains a lot of warnings from `dhall` about missing permissions for cache directories. Those for `/var/empty` are certainly intentional, but what about `/homeless-shelter/.cache`? Is this intentional @Gabriel439?

```
Warning: The directory:

↳ /

... does not give you permission to read, write, or search files.

The directory's current permissions are:
Permissions {readable = True, writable = False, executable = False, searchable = True}


Warning: Could not get or create the default cache directory:

↳ /homeless-shelter/.cache/dhall

You can enable caching by creating it if needed and setting read,
write and search permissions on it or providing another cache base
directory by setting the $XDG_CACHE_HOME environment variable.
```

We could also use the `--no-cache` flag to reduce the number of warnings.

**Comment by Gabriel439** [comment]
@sjakobi: Yes, both warnings are expected if we use `XDG_CACHE_HOME=/var/empty`.  I also agree that using `--no-cache` would be preferable

**Comment by sjakobi** [comment]
Fixed! Tricky stuff, but at least I'm now more familiar with the rules around multi-line strings! ;)

**Pull request merged**
