### PR TITLE
Allow with-expressions to be annotated

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by ocharles** [comment]
Should I add anything else? Should we have parser tests?

**Comment by Gabriel439** [comment]
Yeah, this will need a test.

I think a simpler way to do this would be to keep the `with-expression` rule as-is, and remove `with-expression` from the `expression` rule and instead change the `annotated-expression` rule to:

```abnf
annotated-expression = (operator-expression / with-expression) [ whsp ":" whsp1 expression ]
```

**Comment by ocharles** [comment]
Sure, I can do it that way. I'm not entirely convinced that's simpler, but I'm indifferent on how the syntax is changed to allow this parse 👍

**Comment by Gabriel439** [comment]
Closing as it looks like this has stalled.  Feel free to reopen this if you want to revisit this later

**Pull request closed without merging**
