### PR TITLE
Fix Kind / Sort mistake

### PR DESCRIPTION
**Pull request by SupraSummus**

### CODE REVIEW

**Comment by SupraSummus** [comment]
Please verify this thoroughly, because I've backported this behaviour from dhall-haskell implementation.

```
$ echo '{a: Type}' | dhall type
Kind
```

**Comment by SupraSummus** [comment]
My bad, sorry. Closing this.

**Comment by Gabriel439** [comment]
No problem at all 🙂

**Comment by joneshf** [comment]
Would it be worthwhile to put that explanation in the spec?

**Pull request closed without merging**
