### PR TITLE
Disallow Natural literals with leading zeros

### PR DESCRIPTION
**Pull request by philandstuff**
Currently, we allow parsing literals like `042` as decimal Natural
literals.  This is uncommon (dhall format will remove leading zeros).
It also makes things marginally more tricky for implementations, because
standard libraries often provide functions for parsing C-style numeric
literals, which will handle a leading `0x` correctly, but will assume
that a leading 0 marks an octal literal, so `042` actually means the
same as `34`.

For an example function like this, see Go's [strconv.ParseInt][].

This commit updates the ABNF to require Natural literals to have a
leading nonzero digit, except for 0 itself.  It also removes the one
instance of a leading 0 literal in the tests.

I didn't change hexadecimal literals: 0x00ff is still allowed.  I think
this is fine.

[strconv.ParseInt]: https://golang.org/pkg/strconv/#ParseInt

### CODE REVIEW

**Comment by sjakobi** [comment]
That seems like a pretty pragmatic change. I wonder though whether we should change the `Double` parsing rules similarly for consistency.

**Comment by philandstuff** [comment]
My motivation is as in the PR opening: so I can use `stdconv.ParseInt` in dhall-golang. Hexadecimal and double literals don’t have this problem, so I’m not inclined to disallow leading zeros for them, at least not in this PR.

**Comment by Nadrieril** [comment]
Could you add a parser failure test for the case of a Natural with a leading 0 ?

**Comment by philandstuff** [comment]
@Nadrieril done

**Pull request merged**
