### PR TITLE
Prelude: add functions version of built-in operators

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change adds the `add` function for Natural.

### CODE REVIEW

**Comment by sjakobi** [comment]
Could you say something about the motivation for this addition, @TristanCacqueray?

**Comment by TristanCacqueray** [comment]
This can be use to do function composition with addition, for example to generate a list of natural starting from one, we could write:

```dhall
Prelude.List.generate count Natural (Prelude.Natural.add 1)
```

Instead of:

```dhall
Prelude.List.generate count Natural (\(idx : Natural) -> idx + 1))
```

**Comment by TristanCacqueray** [comment]
I see, then I guess it's better to keep operator out of the Prelude.

**Comment by lisael** [comment]
Maybe we could add a `Prelude.Operator` package to namespace the operator functions? Or `Prelude.<BuiltinType>.Operator` ?

**Comment by Gabriel439** [comment]
@lisael: Yeah, I would be fine with something like that!

**Comment by TristanCacqueray** [comment]
Alright I can work on that, so:

* Prelude.Operator.add (+)
* Prelude.Operator.mul (*)
* Prelude.Operator.or (||)
* Prelude.Operator.and (&&)
* Prelude.Operator.equal (==)
* Prelude.Operator.notEqual (!=)
* Prelude.Operator.append (#)

**Comment by sjakobi** [comment]
+1/2 for `Prelude.Operator` :)

There are some existing names that we can but don't have to reuse in the grammar:

https://github.com/dhall-lang/dhall-lang/blob/5fde8ef1bead6fb4e999d3c1ffe7044cd019d63a/standard/dhall.abnf#L804-L818

Also, don't forget `++`.

**Comment by TristanCacqueray** [comment]
So Operator.TextAppend (++) and Operator.ListAppend (#) ?

**Comment by Gabriel439** [comment]
Another option is that we could name the fields after the operators by quoting the operators with bacticks.  In other words, you could do:

```dhall
Prelude.Operator.`==`
```

However, I'd also be fine with the current names, too

**Comment by lisael** [comment]
Another shower thought is that the operators that are not commutative (namely `++` and `#`) should provide a reversed order function too, to permit currying in both orders.
```hs
let appendText
    : Text → Text → Text
    = λ(m : Text) → λ(n : Text) → n ++ m

let prependText
    : Text → Text → Text
    = λ(m : Text) → λ(n : Text) → m ++ n
```
Note that the name of the function becomes `verbSubject` and that `appendText` is `n ++ m` while `textAppend` was `m ++ n`.

Usage:

```hs
let hostnameToFqdn = λ(hostname : Text) → appendText ".example.com" hostname
```

**Comment by sjakobi** [comment]
> Another option is that we could name the fields after the operators by quoting the operators with bacticks. In other words, you could do:
> 
> ```haskell
> Prelude.Operator.`==`
> ```

I love this idea! This eliminates the problem that some of the current names might be hard to remember. For example `add` could also be named `plus`.

---

@lisael I think we need to find a balance between adding quality-of-life improvements and keeping the Prelude at a size where it's not overly hard to navigate and maintain. Performance is also a relevant concern.

When considering API enhancements in Haskell libraries I sometimes try use the [Fairbairn threshold](https://wiki.haskell.org/Fairbairn_threshold).

So I'm not a fan of adding flipped versions of functions.

We could rather consider adding something like

```dhall
Prelude.Function.flip : ∀(a : Type) → ∀(b : Type) → (a → b) → b → a
```

if anyone would want to use that.

---

Also, do we really want to have a version with the `.dhall` file extension and another one without for each export? I thought keeping the files without the extension was just a backward compatibility measure for the existing API.

**Comment by TristanCacqueray** [comment]
Alright, next commit uses the operator symbols without the extensionless files.

**Comment by sjakobi** [comment]
Thanks @TristanCacqueray! :)

I'm vaguely concerned about filenames like `*.dhall` causing problems – but maybe I shouldn't be!?

Are there any filename experts present? ;)

**Comment by sjakobi** [comment]
https://stackoverflow.com/a/35352640/1013393 indicates that `*.dhall` might indeed cause problem on Windows. Could any Windows users confirm?!

**Comment by TristanCacqueray** [comment]
I named the file after the symbols as a test, but even if that works, I think that can be a source of unexpected problems. So either we pick type neutral name for the filename (and keep the operator symbols in the package.dhall record), either we could pack all the definition directly in the package.dhall record.

**Comment by Gabriel439** [comment]
@TristanCacqueray: I think it would be fine to pack all of the definitions directly in the `package.dhall` record, with a comment explaining why

**Comment by Gabriel439** [comment]
@TristanCacqueray: Not for this repository.  We build `dhall-docs` sample output in CI for the `dhall-haskell` repository

**Comment by sjakobi** [comment]
Maybe it would be more conventional to offer these functions via `Prelude/Operator/package.dhall` instead of `Prelude/Operator.dhall` though.

**Comment by TristanCacqueray** [comment]
Thank you all for the feedbacks, I hope I get the suggestions right in the last commits :-) Please do let me know otherwise.

**Pull request merged**
