### PR TITLE
Remove support for fusion

### PR DESCRIPTION
**Pull request by Gabriel439**
The fusion rules do not trigger reliably (i.e. they are not confluent),
and they complicate the standard, so I propose to remove them to
simplify things for new implementations.

### CODE REVIEW

**Comment by Gabriel439** [comment]
Here is the matching change to the Haskell implementation: https://github.com/dhall-lang/dhall-haskell/pull/1478

**Comment by sjakobi** [comment]
> The fusion rules do not trigger reliably (i.e. they are not confluent)

Can you expand on what you mean with "not confluent"  and how you observed the unreliable triggering?

**Comment by Gabriel439** [comment]
@sjakobi: Here is an example expression I'll use to illustrate:

```dhall
  λ(n : Natural)
→ let example =
          λ ( k
            :   ∀(natural : Type)
              → ∀(succ : natural → natural)
              → ∀(zero : natural)
              → natural
            )
        → Natural/build k
  
  in  example (Natural/fold n)
```

There are two ways we could potentially normalize this code:

* Approach 1
    * Substitute `Natural/fold n` for `k` in the body of `example`
    * Normalize the body of `example`
* Approach 2
    * Normalize the body of `example`
    * Substitute `Natural/fold n` for `k` in the body of `example`
    * Normalize the body of `example`

Approach 1 normalizes to:

```dhal;
λ(n : Natural) → n
```

Approach 2 normalizes to:

```dhall
λ(n : Natural) → Natural/fold n Natural (λ(n : Natural) → n + 1) 0
```

"Confluent" means that the language produces the same result no matter what evaluation strategy you use.  When we use two different evaluation strategies (such as the above two Approaches) and get different normal forms then the language is not confluent.

This also affects us in practice.  For example, fusion often doesn't work in practice due to a phenomenon very similar to "Approach 2".  When we import Prelude expressions protected by semantic integrity checks we pre-normalize them, which causes `*/build` functions within them to prematurely simplify, missing opportunities for build/fold fusion.  This unreliability of optimizations is a classic symptom of the absence of confluence.

**Comment by Gabriel439** [comment]
@sjakobi: You're welcome! :slightly_smiling_face:

**Pull request merged**
