### PR TITLE
Merge `typecheck` and `type-inference` tests

### PR DESCRIPTION
**Pull request by Nadrieril**
Fixes https://github.com/dhall-lang/dhall-lang/issues/536
type-inference tests are strictly more general than typecheck tests, since a typecheck test of `A` against `B` can always be turned into an equivalent type-inference test of `A : B` against `B` (or even of `let _ = A : B in 0` against `Natural` if we want to be pedantic). This PR merges those two types of tests.

### CODE REVIEW

**Comment by Nadrieril** [comment]
I would prefer naming them all `typecheck` instead of `type-inference` because it's shorter, but `type-inference` is definitely clearer...

**Comment by sjakobi** [comment]
> On the second run, the test fails, complaining about non-alpha-normalized variables.

Correction: On the second run, many prelude components are loaded from the cache, and we get _unexpectedly_ alpha-normalized variables.

**Comment by sjakobi** [comment]
Based on [my WIP PR for `dhall-haskell`](https://github.com/dhall-lang/dhall-haskell/pull/1275) this mostly looks fine! The refactoring may even have uncovered [a little bug](https://github.com/dhall-lang/dhall-haskell/issues/1274).

Regarding the caching issue I'd suggest that we somehow ensure an empty cache. Going the import tests' route would mean including the cache for the entire prelude in the source tree, which seems like a disproportionate maintenance burden. On Unix, this can be done by setting `XDG_CACHE_HOME=/var/empty` – not sure what would be the Windows equivalent…

**Comment by Nadrieril** [comment]
Yeah I had to empty the cache to get the `preludeB.dhall` of his PR as well.
There was a discussion I can't find anymore, about whether we should always alpha-normalize the result of an import. That way caching would be unobservable. It would probably be worse for type error messages however.
To go your way, we could just add a line to `tests/README.md` saying that imports should be resolved without caching, and les the implementations figure it out ?

**Comment by sjakobi** [comment]
> There was a discussion I can't find anymore, about whether we should always alpha-normalize the result of an import. That way caching would be unobservable. It would probably be worse for type error messages however.

Yeah, I wouldn't be a fan… ;)

> To go your way, we could just add a line to tests/README.md saying that imports should be resolved without caching, and les the implementations figure it out ?

It feels a bit ad-hoc, but it's probably the pragmatic thing to do for now. :+1:

**Comment by sjakobi** [comment]
@Nadrieril Even after fixing the import resolution in https://github.com/dhall-lang/dhall-haskell/pull/1275, the prelude test doesn't pass without the following patch:

```diff
--- a/tests/type-inference/success/preludeB.dhall
+++ b/tests/type-inference/success/preludeB.dhall
@@ -398,7 +398,7 @@
     }
 , XML :
     { attribute :
-        Text → Text → { mapKey : Text, mapValue : Text }
+        ∀(key : Text) → ∀(value : Text) → { mapKey : Text, mapValue : Text }
     , element :
           ∀ ( elem
             : { attributes :
```

Now I'm not sure whether the Haskell implementation doesn't follow the standard or whether the expected test output is wrong.

**Comment by Gabriel439** [comment]
@sjakobi: I'm reasonably certain that the correct type to infer is `∀(key : Text) → ∀(value : Text) → …`

The reason the `attribute` utility has named parameters was that it was defined differently from the other XML utilities, since it's just a naked function:

https://github.com/dhall-lang/dhall-lang/blob/edd2fcb86f725942a34e6928ea4a749ec7c35a3c/Prelude/XML/attribute#L1-L3

... and when you infer the type of a function the ∀-bound variables have the same name as the λ-bound variables.

Contrast that with the other XML utilities, which typically define a `let` binding (consistent with the rest of the Prelude), like this one:

https://github.com/dhall-lang/dhall-lang/blob/edd2fcb86f725942a34e6928ea4a749ec7c35a3c/Prelude/XML/leaf#L20-L32

When you do that, the inferred type is exactly the type given to the `let`-bound variable, rather than the inferred type of the right-hand-side of the `let` binding.  The former has bound variables named `_` and the latter does not.

So if you want to fix the discrepancy, the idiomatic solution here is to refactor `XML/attribute` to use the `let` idiom like the rest of the Prelude does.

**Comment by sjakobi** [comment]
Thanks for the explanation @Gabriel439!

> So if you want to fix the discrepancy, the idiomatic solution here is to refactor `XML/attribute` to use the `let` idiom like the rest of the Prelude does.

Could it be that even after the refactoring, the correct type is

    ∀(key : Text) → ∀(value : Text) → { mapKey : Text, mapValue : Text }

because the type of an import is inferred from the normalized expression?

**Comment by Gabriel439** [comment]
@sjakobi: I'm not sure

**Comment by sjakobi** [comment]
I think that's what's happening, at least in the Haskell implementation: `dhall resolve` normalizes any imports.

However in the imports spec I can only find mentions of normalization in the context of headers and caching.

**Pull request merged**
