### PR TITLE
Remove referential sanity check

### PR DESCRIPTION
**Pull request by philandstuff**
As I was implementing imports, I realised that the referential sanity
check is strictly more permissive than the CORS check.  This means we
don't need it, because anything which is not referentially sane will
also fail the CORS check.

This makes the import semantics simpler to describe, without changing
its meaning.

I also changed the "referentiallyInsane" test to try to use less of the
"referential sanity" language, since that terminology is no longer
defined in the semantics.

I've made this a draft PR because I want to get a sense from people if they
think this is a good change in principle first.  Then, if people think this makes
sense in principle, I'd like to look in more detail at the language.  For example,
some of the existing text in the "referential sanity check" section is probably
still valuable and could be ported over to the CORS check section.

### CODE REVIEW

**Comment by singpolyma** [comment]
Does the CORS check say anything about environment variables? I thought the purpose of the CORS ickiness was to avoid behind-the-firewall HTTP stuff that would normally otherwise work.

**Comment by philandstuff** [comment]
I added some text to the CORS check section to explain my thinking:

> Note well that there is no inference rule that allows a remote parent
requesting a local child to be corsCompliant().

"CORS checking" in the original sense is about one origin fetching resources from another, so it would say nothing about environment variables or local files.

However, our `corsCompliant()` judgment is about one *import* fetching another, and it has explicit rules saying that local imports can fetch remote imports, and it conspiciously doesn't have any inference rule allowing a remote import to fetch a local.

It might be worth renaming `corsCompliant` to be something else to make this less confusing. Maybe we should rename `corsCompliant` to `referentiallySane` once we've got rid of the existing `referentiallySane`?

To be clear: my point is that, based on the current `corsCompliant()` and `referentiallySane()` judgments, we can prove `corsCompliant()` implies `referentiallySane()`, and because we require all imports to be `corsCompliant()` we don't need to also test if they are `referentiallySane()`.

**Comment by philandstuff** [comment]
I haven’t forgotten about this, but as I started work on expanding it I realised I needed to think more about it. I’ll leave it as a draft PR but don’t expect much movement for a while

**Comment by philandstuff** [comment]
I pushed my work in progress, but this definitely isn't ready for merge yet

**Comment by philandstuff** [comment]
I've dropped the ball on this.  Closing, though I may reopen (or open something similar) in future.

**Pull request closed without merging**
