### PR TITLE
Add support for leading separators

### PR DESCRIPTION
**Pull request by Gabriel439**
Related to #512

This change adds support for leading (but not trailing) commas and bars

### CODE REVIEW

**Comment by Gabriel439** [comment]
Matching change to the Haskell implementation here: https://github.com/dhall-lang/dhall-haskell/pull/1355

**Comment by Gabriel439** [comment]
The main reason that I didn't also standardize support for trailing separators is primarily because it's more difficult.  Since I don't plan to use trailing separators in the Haskell formatter I didn't want to invest the effort to standardize them.  However, if somebody wants to follow-up with a change to standardize trailing separators I won't oppose it.

**Comment by Gabriel439** [comment]
@sjakobi: I plan on changing the pretty printer to definitely use leading separators for the `T::r` syntax discussed in https://github.com/dhall-lang/dhall-lang/pull/755.  I might also use them for ordinary records, too, but I haven't decided on that yet.

**Comment by singpolyma** [comment]
Does this make it any harder to add trailing later?

**Comment by Gabriel439** [comment]
@singpolyma: I can't say for sure, but I believe it's still roughly the same difficulty to add trailing delimiters before and after this change

**Comment by neongreen** [comment]
@Gabriel439 can you give an example of how canonical formatting will look with leading separators?

**Comment by Gabriel439** [comment]
@neongreen: Initially there will be no changes (see the matching pull request for the Haskell implementation, which does not change the pretty-printing logic)

One I finish standardizing support for record completion in #767 I will adjust the formatting of record completion to look like this:

```haskell
Example::{
  , foo = 1
  , bar = True
}
```

... but leave normal records still formatted the same way.  Then I'll wait and see if people ask me to also format normal records the same way or not

**Pull request merged**
