### PR TITLE
Renamed Directory.dhall and File.dhall

### LINKED ISSUE #1321: Case sensitive filename collision makes this repo unusable on case insensitive FS
The files `Prelude/DirectoryTree/Entry/Directory.dhall` and `Prelude/DirectoryTree/Entry/directory.dhall` are treated as the same file by case-insensitive filesystems, such as the default on macOS. `Prelude/DirectoryTree/Entry/File.dhall` and `Prelude/DirectoryTree/Entry/file.dhall` have the same problem.

This essentially means it's not possible to use this repository on a case-insensitive filesystem.

### PR DESCRIPTION
**Pull request by mmhat**
Those file names led to conflicts on case-insensitive filesystems.

Fixes #1321

### CODE REVIEW

**Review by Gabriella439 — APPROVED** [review]
Looks good to me.  Just wait a week before merging since this is a change to the Prelude

**Comment by sjakobi** [comment]
It would be useful to add a check for case-insensitive duplicate files to the CI setup.

**Comment by mmhat** [comment]
> It would be useful to add a check for case-insensitive duplicate files to the CI setup.

I used
```bash
find Prelude | tr '[:upper:]' '[:lower:]' | sort | uniq -c | grep -v '^ *1'
```
as a quick check for that. I like the idea of adding something like that to the CI, but I am not familiar with the setup. I suppose it should be included [here](https://github.com/dhall-lang/dhall-lang/blob/910807866d85803345f4b65a8cb8bc8add24c9fa/nixops/overlay.nix#L475)?

**Comment by sjakobi** [comment]
> I suppose it should be included [here](https://github.com/dhall-lang/dhall-lang/blob/910807866d85803345f4b65a8cb8bc8add24c9fa/nixops/overlay.nix#L475)?

Yes, that's the spot I would suggest too.

**Comment by mmhat** [comment]
@Gabriella439 @sjakobi I think this one can be merged.

**Comment by Gabriella439** [comment]
Sorry about that!  I added you as a collaborator, so you should be able to merge now

**Comment by mmhat** [comment]
@Gabriella439 Thank you!

**Pull request merged**
