### PR TITLE
Prelude: Document connection to Monoid for Bool/even and Bool/odd

### PR DESCRIPTION
**Pull request by sjakobi**
Background:
https://discourse.dhall-lang.org/t/whats-up-with-bool-even-and-bool-odd/54

### CODE REVIEW

**Comment by sjakobi** [comment]
Since this is not a standard change, is this good to merge already?

**Comment by Gabriel439** [comment]
@sjakobi: Changes to the Prelude are treated the same way as changes to the standard.  See: https://github.com/dhall-lang/dhall-lang/blob/master/.github/CONTRIBUTING.md#how-do-changes-get-approved

**Comment by sjakobi** [comment]
Oops, I misremembered that. Thanks for clearing it up @Gabriel439! :)

**Comment by Gabriel439** [comment]
@sjakobi: You're welcome! 🙂

**Pull request merged**
