### PR TITLE
added Function/sequence

### PR DESCRIPTION
**Pull request by shimib**

### CODE REVIEW

**Comment by sjakobi** [comment]
This looks like a special variant of `Prelude.List.map`:

```
⊢ Prelude.List.map (Natural -> Text) Text (\(f : Natural -> Text) -> f 42) [ Natural/show ]

[ "42" ]
```

Is there a particular reason why it should be included in the Prelude?

Also, is there some precedent for the name? `sequence` makes me think of Haskell's `Traversable` type class, but this seems unrelated.

**Comment by shimib** [comment]
Actually it's the instance of `sequence` from `Traversable` where `t` is `List` and the `Applicative` is `Function`.
I don't think we can currently implement higher-kinded-types in Dhall.
Usually I find `Function.sequence` :: `List[A -> B] -> A -> List[B]`
and `Option.sequence` :: `List[Option A] -> Option[List[A]]` be very useful.

**Comment by sjakobi** [comment]
> Actually it's the instance of `sequence` from `Traversable` where `t` is `List` and the `Applicative` is `Function`.

Oh, thanks for pointing that out!

> I don't think we can currently implement higher-kinded-types in Dhall.

I thought, `dhall-bhat` contained something like this: https://github.com/FormationAI/dhall-bhat/tree/master/Traversable

**Comment by shimib** [comment]
Still new to the language. Wasn't familiar with this library. Thanks for pointing it :)

**Pull request closed without merging**
