### PR TITLE
Add testcase for dhall-lang/dhall-haskell#1278

### PR DESCRIPTION
**Pull request by sjakobi**
See dhall-lang/dhall-haskell#1278.

The file location is based on #723.

### CODE REVIEW

**Comment by sjakobi** [comment]
Oops, I meant `toMap { x = Bool }`, not `toMap { x : Bool }`! :/ :smile:

**Comment by philandstuff** [comment]
This is quite a different test now. Is there a reason you’re adding a test to ensure toMap must be run on records of `Type`s, rather than changing the standard so that toMap works on any record? I feel like either would be a sensible choice but I’d like to know your thinking.

**Comment by sjakobi** [comment]
Note that this is a failure test! We can't run `toMap` on a record of types, since the resulting list would be a `List`  of types, which we don't currently allow!

**Comment by sjakobi** [comment]
There is some discussion regarding lists of types in https://github.com/dhall-lang/dhall-lang/issues/693.

**Comment by philandstuff** [comment]
Ah yes, good point. Carry on

**Pull request merged**
