### PR TITLE
Version 8.0.0 → 9.0.0

### PR DESCRIPTION
**Pull request by Gabriel439**
It's been over 30 days since the last release of the standard, so I'm starting the process to cut the next release.

The one feature I definitely plan to wait for is:

* [x] #610: Add `toMap` keyword to create homogeneous maps from records

... if only because I wrote the rest of the `CHANGELOG` assuming the feature was merged :slightly_smiling_face: 

For other changes in progress I'll include them if they make it in before that or before the waiting period is over (i.e. 3 days since last change).

Edit: Also waiting for:

* [x] #639: Remove `./Prelude/Map.dhall`
* [x] #640: Forbid surrogate pairs and non-characters
* [x] #641: Fix `toMap` normalization test
* [x] #644: Use 28 for empty lists with non-`List` annotations
* [x] #645: Fix grammar for empty list literals
* [x] #651: Fix type-inference for `toMap`
* [x] #652: Fix first-application-expression rule
* [x] #654: Fix `ListLitEmptyPrecedence` parsing test

### CODE REVIEW

**Comment by singpolyma** [comment]
I think I have everything but toMap implemented in dhall-ruby -- I will try to actually get a matching release out this time.

**Comment by singpolyma** [comment]
Should we also standardize banning surrogates and other non-codepoints before this release? Shouldn't be a big change and goes hand-in-hand with the new `\u{...}` and removing mention of surrogates from ABNF that already went in.

**Comment by Gabriel439** [comment]
@singpolyma: Yeah, I can include that

**Comment by Gabriel439** [comment]
Alright, I'm going to cut this release in 3 days assuming no new fixes come in (and update the `CHANGELOG.md` in the meantime).  I'm only going to ask @ocharles to hold off on merging #650 until after 8.0.0 (mainly to avoid resetting the 3-day wait after each merged change to the standard).

**Comment by ocharles** [comment]
Fine with me!

**Comment by sjakobi** [comment]
Should #630 be mentioned in the changelog?

**Comment by Gabriel439** [comment]
@sjakobi: Yes, I plan to update the changelog before cutting the release to reflect the recently merged pull requests

**Comment by Gabriel439** [comment]
@sjakobi: Alright, I updated the `CHANGELOG` to reflect the recent changes

**Pull request merged**
