### PR TITLE
Add Unicode support for quoted path characters

### PR DESCRIPTION
**Pull request by Gabriel439**
Fixes https://github.com/dhall-lang/dhall-haskell/issues/798

This extends the range of quoted paths from ASCII to Unicode

### CODE REVIEW

**Comment by fosskers** [comment]
Tonight, to test this, I can attempt wrangling the submodule in `dhall-haskell` that points here.

**Comment by Gabriel439** [comment]
@fosskers: Note that the Haskell code does not directly use the `dhall.abnf` file.  You'd have to modify the Haskell parser, which I plan to do anyway in a matching pull request soon

**Comment by fosskers** [comment]
Ah, gotcha. I had assumed some futuristic scenario where the Haskell could divine a legal parser from the `.abnf`.

**Comment by Gabriel439** [comment]
Here is the matching change to the Haskell implementation: https://github.com/dhall-lang/dhall-haskell/pull/800

**Pull request merged**
